import {notFound} from "next/navigation";
import {adminModules,permissionGroups} from "../../_data/admin";
import {db} from "../../_lib/db";
import {databaseHealth} from "../../_lib/cms";
import {createEvent,createFormDefinition,createLeadership,createMedia,createNavigation,createPartner,createPost,createProgram,createProject,saveSiteSetting,updateMemberStatus} from "./actions";

export const dynamic="force-dynamic";
export function generateStaticParams(){return adminModules.filter(m=>!["pages","themes","plugins"].includes(m.slug)).map(m=>({module:m.slug}))}

const Empty=({title,children}:{title:string;children:React.ReactNode})=><div className="admin-empty"><strong>{title}</strong>{children}</div>;
const Section=({title,children}:{title:string;children:React.ReactNode})=><section className="admin-panel"><div className="admin-panel-head"><h2>{title}</h2></div>{children}</section>;
const Input=({name,label,type="text",required=false,placeholder}:{name:string;label:string;type?:string;required?:boolean;placeholder?:string})=><label>{label}<input name={name} type={type} required={required} placeholder={placeholder}/></label>;

function Roles(){return <><div className="admin-permission-grid">{permissionGroups.map(g=><article className="admin-permission-group" key={g.name}><h3>{g.name}</h3><ul>{g.permissions.map(p=><li key={p}>{p}</li>)}</ul></article>)}</div><Section title="Access-control principles"><div className="admin-info-grid"><article><strong>Least privilege</strong><p>Give staff only the permissions required for their role.</p></article><article><strong>Approval boundaries</strong><p>Publishing, finance and role management should remain restricted.</p></article><article><strong>Traceability</strong><p>Administrative changes should be backed by audit records.</p></article></div></Section></>}

async function System(){const health=await databaseHealth();const [users,pages,logs,media]=await Promise.all([db.user.count(),db.page.count(),db.auditLog.count(),db.mediaAsset.count()]);return <><div className="admin-stat-grid"><article className="admin-stat"><small>DATABASE</small><strong>{health.ok?"Online":"Issue"}</strong><span>{health.ok?`${health.latency}ms response`:"Check DATABASE_URL"}</span></article><article className="admin-stat"><small>USERS</small><strong>{users}</strong><span>Database accounts</span></article><article className="admin-stat"><small>CMS PAGES</small><strong>{pages}</strong><span>Persistent records</span></article><article className="admin-stat"><small>AUDIT EVENTS</small><strong>{logs}</strong><span>{media} media records</span></article></div><div className="admin-grid"><Section title="Environment readiness"><div className="admin-config-list"><div className="admin-status-row"><span>Admin credentials</span><b className="admin-status-good">Configured</b></div><div className="admin-status-row"><span>PostgreSQL / Neon</span><b className={health.ok?"admin-status-good":"admin-status-pending"}>{health.ok?"Connected":"Connection issue"}</b></div><div className="admin-status-row"><span>Prisma schema</span><b className="admin-status-good">Enabled</b></div><div className="admin-status-row"><span>Page revisions</span><b className="admin-status-good">Persistent</b></div><div className="admin-status-row"><span>Audit logging</span><b className="admin-status-good">Persistent</b></div><div className="admin-status-row"><span>Media file hosting</span><b className="admin-status-pending">URL/library mode</b></div></div></Section><Section title="Runtime configuration"><div className="admin-config-list"><code>MWONET_ADMIN_EMAIL ✓</code><code>MWONET_ADMIN_PASSWORD ✓</code><code>MWONET_ADMIN_SESSION_SECRET ✓</code><code>DATABASE_URL ✓</code></div><p className="admin-section-note">Sensitive values stay in Vercel and are never displayed by the application.</p></Section></div></>}

async function Users(){const users=await db.user.findMany({orderBy:{createdAt:"desc"},take:100,include:{roles:{include:{role:true}},member:true}});return <><div className="admin-stat-grid"><article className="admin-stat"><small>TOTAL USERS</small><strong>{users.length}</strong><span>Loaded accounts</span></article><article className="admin-stat"><small>ACTIVE</small><strong>{users.filter(x=>x.status==="ACTIVE").length}</strong><span>Enabled accounts</span></article><article className="admin-stat"><small>MEMBERS</small><strong>{users.filter(x=>x.member).length}</strong><span>Linked profiles</span></article><article className="admin-stat"><small>ADMINS</small><strong>{users.filter(x=>x.roles.length).length}</strong><span>Role-assigned users</span></article></div><Section title="User directory"><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Member</th><th>Last sign-in</th></tr></thead><tbody>{users.length?users.map(u=><tr key={u.id}><td><strong>{u.name||"Unnamed user"}</strong><small>{u.email}</small></td><td>{u.roles.map(r=>r.role.name).join(", ")||"—"}</td><td><span className="admin-badge">{u.status}</span></td><td>{u.member?.memberNumber||u.member?.status||"—"}</td><td>{u.lastLoginAt?u.lastLoginAt.toLocaleString("en-KE"):"Never"}</td></tr>):<tr><td colSpan={5}><Empty title="No users yet">Portal and staff accounts will appear here.</Empty></td></tr>}</tbody></table></div></Section></>}

async function Members(){const members=await db.memberProfile.findMany({orderBy:{joinedAt:"desc"},take:100,include:{user:true}});return <><div className="admin-stat-grid"><article className="admin-stat"><small>TOTAL</small><strong>{members.length}</strong><span>Member records</span></article><article className="admin-stat"><small>PENDING</small><strong>{members.filter(x=>x.status==="PENDING").length}</strong><span>Awaiting review</span></article><article className="admin-stat"><small>ACTIVE</small><strong>{members.filter(x=>x.status==="ACTIVE").length}</strong><span>Approved members</span></article><article className="admin-stat"><small>CONSTITUTION</small><strong>18–35</strong><span>Eligibility age range</span></article></div><Section title="Membership registry"><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Member</th><th>Number</th><th>County</th><th>Status</th><th>Fees</th><th>Action</th></tr></thead><tbody>{members.length?members.map(m=><tr key={m.id}><td><strong>{m.user.name||"Unnamed"}</strong><small>{m.user.email}{m.phone?` · ${m.phone}`:""}</small></td><td>{m.memberNumber||"Pending"}</td><td>{m.county||"—"}</td><td><span className="admin-badge">{m.status}</span></td><td><small>Registration KSh {m.registrationFee?.toString()||"—"}<br/>Monthly KSh {m.monthlyFee?.toString()||"—"}</small></td><td><form action={updateMemberStatus} className="admin-inline-form"><input type="hidden" name="id" value={m.id}/><select name="status" defaultValue={m.status}><option>PENDING</option><option>ACTIVE</option><option>INACTIVE</option><option>SUSPENDED</option><option>TERMINATED</option></select><button className="admin-secondary">Save</button></form></td></tr>):<tr><td colSpan={6}><Empty title="No member records yet">Pending and approved membership records will appear here.</Empty></td></tr>}</tbody></table></div></Section><Section title="Membership policy reference"><div className="admin-info-grid"><article><strong>Registration</strong><p>KSh 1,000 constitutional registration fee.</p></article><article><strong>Monthly subscription</strong><p>KSh 200 constitutional monthly subscription.</p></article><article><strong>Administration</strong><p>Use status changes carefully and maintain supporting records.</p></article></div></Section></>}

async function Audit(){const logs=await db.auditLog.findMany({orderBy:{createdAt:"desc"},take:200,include:{actor:true}});return <Section title="Administrative activity"><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Resource</th><th>ID</th></tr></thead><tbody>{logs.length?logs.map(l=><tr key={l.id}><td>{l.createdAt.toLocaleString("en-KE")}</td><td>{l.actor?.email||"System"}</td><td><strong>{l.action}</strong></td><td>{l.resource}</td><td><code>{l.resourceId||"—"}</code></td></tr>):<tr><td colSpan={5}><Empty title="No audit records yet">CMS and administration actions will be recorded here.</Empty></td></tr>}</tbody></table></div></Section>}

async function Programs(){const rows=await db.program.findMany({orderBy:{title:"asc"},include:{_count:{select:{projects:true}}}});return <><Section title="Add program"><form action={createProgram} className="admin-form admin-form-grid"><Input name="title" label="Program title" required/><Input name="slug" label="Slug (optional)"/><label className="admin-span-2">Summary<textarea name="summary" rows={3}/></label><button className="admin-primary">Create program</button></form></Section><Section title="Program portfolio"><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Program</th><th>Slug</th><th>Projects</th><th>Summary</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><strong>{x.title}</strong></td><td><code>{x.slug}</code></td><td>{x._count.projects}</td><td>{x.summary||"—"}</td></tr>)}</tbody></table></div></Section></>}

async function Projects(){const [rows,programs]=await Promise.all([db.project.findMany({orderBy:{title:"asc"},include:{program:true}}),db.program.findMany({orderBy:{title:"asc"}})]);return <><Section title="Create project"><form action={createProject} className="admin-form admin-form-grid"><Input name="title" label="Project title" required/><Input name="slug" label="Slug (optional)"/><label>Program<select name="programId"><option value="">Unassigned</option>{programs.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><Input name="location" label="Location"/><Input name="startDate" label="Start date" type="date"/><Input name="endDate" label="End date" type="date"/><label className="admin-span-2">Summary<textarea name="summary" rows={3}/></label><button className="admin-primary">Create project</button></form></Section><Section title="Project register"><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Project</th><th>Program</th><th>Status</th><th>Location</th><th>Dates</th></tr></thead><tbody>{rows.length?rows.map(x=><tr key={x.id}><td><strong>{x.title}</strong><small>{x.slug}</small></td><td>{x.program?.title||"—"}</td><td><span className="admin-badge">{x.status}</span></td><td>{x.location||"—"}</td><td>{x.startDate?.toLocaleDateString("en-KE")||"—"}{x.endDate?` → ${x.endDate.toLocaleDateString("en-KE")}`:""}</td></tr>):<tr><td colSpan={5}><Empty title="No projects yet">Create the first field project above.</Empty></td></tr>}</tbody></table></div></Section></>}

async function Posts(){const rows=await db.post.findMany({orderBy:{createdAt:"desc"},take:100});return <><Section title="Create news story"><form action={createPost} className="admin-form admin-form-grid"><Input name="title" label="Headline" required/><Input name="slug" label="Slug (optional)"/><label>Status<select name="status" defaultValue="DRAFT"><option>DRAFT</option><option>REVIEW</option><option>PUBLISHED</option></select></label><label className="admin-span-2">Excerpt<textarea name="excerpt" rows={2}/></label><label className="admin-span-2">Story<textarea name="content" rows={7}/></label><button className="admin-primary">Save story</button></form></Section><Section title="Newsroom"><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Title</th><th>Status</th><th>Published</th><th>Updated</th></tr></thead><tbody>{rows.length?rows.map(x=><tr key={x.id}><td><strong>{x.title}</strong><small>{x.slug}</small></td><td><span className="admin-badge">{x.status}</span></td><td>{x.publishedAt?.toLocaleString("en-KE")||"—"}</td><td>{x.updatedAt.toLocaleString("en-KE")}</td></tr>):<tr><td colSpan={4}><Empty title="No news posts yet">Create field stories, announcements and updates.</Empty></td></tr>}</tbody></table></div></Section></>}

async function Events(){const rows=await db.event.findMany({orderBy:{startsAt:"desc"},take:100});return <><Section title="Create event"><form action={createEvent} className="admin-form admin-form-grid"><Input name="title" label="Event title" required/><Input name="slug" label="Slug (optional)"/><Input name="venue" label="Venue"/><Input name="startsAt" label="Starts" type="datetime-local" required/><Input name="endsAt" label="Ends" type="datetime-local"/><label>Status<select name="status" defaultValue="DRAFT"><option>DRAFT</option><option>REVIEW</option><option>PUBLISHED</option></select></label><label className="admin-span-2">Description<textarea name="description" rows={3}/></label><button className="admin-primary">Create event</button></form></Section><Section title="Event calendar records"><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Event</th><th>Status</th><th>Venue</th><th>Starts</th><th>Ends</th></tr></thead><tbody>{rows.length?rows.map(x=><tr key={x.id}><td><strong>{x.title}</strong><small>{x.slug}</small></td><td><span className="admin-badge">{x.status}</span></td><td>{x.venue||"—"}</td><td>{x.startsAt.toLocaleString("en-KE")}</td><td>{x.endsAt?.toLocaleString("en-KE")||"—"}</td></tr>):<tr><td colSpan={5}><Empty title="No events yet">Create the first MWONET event above.</Empty></td></tr>}</tbody></table></div></Section></>}

async function Forms(){const rows=await db.form.findMany({orderBy:{name:"asc"},include:{_count:{select:{submissions:true}}}});return <><Section title="Create form"><form action={createFormDefinition} className="admin-form admin-form-grid"><Input name="name" label="Form name" required/><Input name="key" label="Key (optional)"/><label className="admin-span-2">Fields (comma separated)<textarea name="fields" rows={3} placeholder="name, email, phone, message"/></label><button className="admin-primary">Create form</button></form></Section><Section title="Form library"><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Form</th><th>Key</th><th>Submissions</th></tr></thead><tbody>{rows.length?rows.map(x=><tr key={x.id}><td><strong>{x.name}</strong></td><td><code>{x.key}</code></td><td>{x._count.submissions}</td></tr>):<tr><td colSpan={3}><Empty title="No forms yet">Build contact, volunteer, partner and membership forms.</Empty></td></tr>}</tbody></table></div></Section></>}

async function Media(){const rows=await db.mediaAsset.findMany({orderBy:{createdAt:"desc"},take:100,include:{uploader:true}});return <><Section title="Add media asset"><p className="admin-section-note">Current zero-cost mode stores reusable image/video/document URLs and metadata. Direct binary upload can be connected later to an external storage provider.</p><form action={createMedia} className="admin-form admin-form-grid"><Input name="url" label="Media URL" required/><label>Type<select name="type"><option value="image">Image</option><option value="video">Video</option><option value="document">Document</option></select></label><Input name="title" label="Title"/><Input name="altText" label="Alt text"/><Input name="tags" label="Tags" placeholder="mount elgon, nursery, youth"/><label className="admin-span-2">Caption<textarea name="caption" rows={2}/></label><button className="admin-primary">Add to library</button></form></Section><Section title="Media library"><div className="admin-media-grid">{rows.length?rows.map(x=><article className="admin-media-card" key={x.id}><div className="admin-media-thumb">{x.type==="image"?<img src={x.url} alt={x.altText||x.title||"MWONET media"}/>:<span>{x.type.toUpperCase()}</span>}</div><div><strong>{x.title||"Untitled asset"}</strong><small>{x.tags.join(" · ")||x.type}</small><p>{x.caption||x.altText||"No description"}</p></div></article>):<Empty title="Media library is empty">Add your first professional photo or document above.</Empty>}</div></Section></>}

async function Navigation(){const rows=await db.navigationItem.findMany({orderBy:[{location:"asc"},{order:"asc"}]});return <><Section title="Add navigation item"><form action={createNavigation} className="admin-form admin-form-grid"><Input name="label" label="Label" required/><Input name="href" label="Link / path" required placeholder="/about"/><label>Location<select name="location"><option value="header">Header</option><option value="footer">Footer</option><option value="portal">Portal</option></select></label><Input name="order" label="Order" type="number"/><button className="admin-primary">Add menu item</button></form></Section><Section title="Navigation map"><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Label</th><th>Link</th><th>Location</th><th>Order</th><th>Visible</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><strong>{x.label}</strong></td><td><code>{x.href}</code></td><td>{x.location}</td><td>{x.order}</td><td>{x.visible?"Yes":"No"}</td></tr>)}</tbody></table></div></Section></>}

async function Leadership(){const rows=await db.leadershipProfile.findMany({orderBy:[{order:"asc"},{name:"asc"}]});return <><Section title="Add leadership profile"><form action={createLeadership} className="admin-form admin-form-grid"><Input name="name" label="Full name" required/><Input name="role" label="Official role" required/><Input name="photoUrl" label="Photo URL"/><Input name="email" label="Email" type="email"/><Input name="phone" label="Phone"/><Input name="order" label="Display order" type="number"/><label className="admin-span-2">Biography<textarea name="bio" rows={4}/></label><button className="admin-primary">Add leader</button></form></Section><Section title="Leadership directory"><div className="admin-profile-grid">{rows.length?rows.map(x=><article className="admin-profile-card" key={x.id}>{x.photoUrl?<img src={x.photoUrl} alt={x.name}/>:<div className="admin-profile-placeholder">{x.name.slice(0,1)}</div>}<div><span className="admin-badge">{x.role}</span><h3>{x.name}</h3><p>{x.bio||"Biography pending."}</p><small>{[x.email,x.phone].filter(Boolean).join(" · ")}</small></div></article>):<Empty title="Leadership profiles pending">Add only verified official leaders and approved biographies.</Empty>}</div></Section></>}

async function Partners(){const rows=await db.partner.findMany({orderBy:{name:"asc"}});return <><Section title="Add partner / collaborator"><form action={createPartner} className="admin-form admin-form-grid"><Input name="name" label="Organization name" required/><Input name="category" label="Category" placeholder="Partner, donor, government, community"/><Input name="website" label="Website"/><Input name="logoUrl" label="Logo URL"/><label className="admin-span-2">Description<textarea name="description" rows={3}/></label><button className="admin-primary">Add partner</button></form></Section><Section title="Partner directory"><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Name</th><th>Category</th><th>Website</th><th>Status</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><strong>{x.name}</strong><small>{x.description||"—"}</small></td><td>{x.category||"—"}</td><td>{x.website||"—"}</td><td><span className="admin-badge">{x.active?"Active":"Inactive"}</span></td></tr>)}</tbody></table></div></Section></>}

async function Settings(){const rows=await db.siteSetting.findMany({orderBy:{key:"asc"}});return <><Section title="Global site setting"><form action={saveSiteSetting} className="admin-form admin-form-grid"><Input name="key" label="Setting key" required placeholder="contact.phone"/><label className="admin-span-2">Value<textarea name="value" rows={3} required/></label><button className="admin-primary">Save setting</button></form></Section><Section title="Stored settings"><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Key</th><th>Value</th><th>Updated</th></tr></thead><tbody>{rows.length?rows.map(x=><tr key={x.key}><td><code>{x.key}</code></td><td><small>{JSON.stringify(x.value)}</small></td><td>{x.updatedAt.toLocaleString("en-KE")}</td></tr>):<tr><td colSpan={3}><Empty title="No custom settings yet">Global organization settings can be added above.</Empty></td></tr>}</tbody></table></div></Section></>}

async function Email(){return <><div className="admin-stat-grid"><article className="admin-stat"><small>OFFICIAL DOMAIN</small><strong>mwonet.org</strong><span>Active domain</span></article><article className="admin-stat"><small>RECEIVING</small><strong>Live</strong><span>Cloudflare Email Routing</span></article><article className="admin-stat"><small>OUTBOUND</small><strong>Pending</strong><span>Full mailbox/SMTP not purchased</span></article><article className="admin-stat"><small>PUBLIC ADDRESS</small><strong>info@</strong><span>Forwarding route</span></article></div><Section title="Communication status"><div className="admin-info-grid"><article><strong>Incoming email</strong><p>Official addresses can receive mail through Cloudflare routing and forward to verified destination mailboxes.</p></article><article><strong>Outgoing identity</strong><p>Sending authenticated mail as @mwonet.org requires a proper outbound mailbox/SMTP service. This remains intentionally pending.</p></article><article><strong>Future communications</strong><p>This module is reserved for templates, newsletters, alerts and approved integrations.</p></article></div></Section></>}

async function Seo(){const pages=await db.page.findMany({orderBy:{title:"asc"}});return <><div className="admin-stat-grid"><article className="admin-stat"><small>PAGES</small><strong>{pages.length}</strong><span>CMS pages</span></article><article className="admin-stat"><small>SEO TITLES</small><strong>{pages.filter(x=>x.seoTitle).length}</strong><span>Configured</span></article><article className="admin-stat"><small>DESCRIPTIONS</small><strong>{pages.filter(x=>x.description).length}</strong><span>Configured</span></article><article className="admin-stat"><small>SOCIAL IMAGES</small><strong>{pages.filter(x=>x.socialImage).length}</strong><span>Configured</span></article></div><Section title="SEO coverage"><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Page</th><th>SEO title</th><th>Description</th><th>Social image</th></tr></thead><tbody>{pages.map(x=><tr key={x.id}><td><strong>{x.title}</strong><small>/{x.slug==="home"?"":x.slug.replaceAll("--","/")}</small></td><td>{x.seoTitle?"✓":"Missing"}</td><td>{x.description?"✓":"Missing"}</td><td>{x.socialImage?"✓":"Missing"}</td></tr>)}</tbody></table></div></Section></>}

function Finance(){return <><Section title="Finance architecture"><div className="admin-info-grid"><article><strong>Member subscriptions</strong><p>Prepare registration and monthly-subscription tracking with approval controls.</p></article><article><strong>Savings & revolving fund</strong><p>Future ledgers should preserve constitutional rules, guarantorship and transaction evidence.</p></article><article><strong>Auditability</strong><p>Financial records should never be silently editable; approvals and history are required.</p></article></div></Section><Section title="Safety gate"><p className="admin-section-note">The finance UI is intentionally not creating live money records yet. Before activation we should define transaction types, approval roles, receipts, reversals, reconciliation and reporting so financial data cannot be corrupted.</p></Section></>}

function Reports(){return <><Section title="Reporting centre"><div className="admin-info-grid"><article><strong>Membership</strong><p>Active, pending, age/location distribution and participation summaries.</p></article><article><strong>Programs & projects</strong><p>Activities, milestones, project status, location and evidence reporting.</p></article><article><strong>Website & communications</strong><p>Content publishing, forms, events and future engagement metrics.</p></article><article><strong>Finance</strong><p>Future approved ledgers, contribution statements and revolving-fund reports.</p></article></div></Section><Section title="Export roadmap"><div className="admin-quick-grid"><span className="admin-section-note">PDF reports</span><span className="admin-section-note">CSV export</span><span className="admin-section-note">Date filters</span><span className="admin-section-note">Print layouts</span></div></Section></>}

function Notifications(){return <><Section title="Notification channels"><div className="admin-info-grid"><article><strong>In-app</strong><p>Announcements and account notices inside the future member portal.</p></article><article><strong>Email</strong><p>Transactional and bulk email requires an approved outbound provider.</p></article><article><strong>SMS / Push</strong><p>Can be connected later when a provider and budget are approved.</p></article></div></Section><Section title="Communication controls"><p className="admin-section-note">No paid notification provider is enabled. This workspace keeps the architecture ready without creating recurring costs.</p></Section></>}

function DefaultModule({label}:{label:string}){return <><Section title={`${label} workspace`}><Empty title="Structured workspace ready">This module is included in the admin architecture and can be expanded without changing navigation.</Empty></Section><Section title="Management controls"><div className="admin-quick-grid"><span className="admin-section-note">Create & edit</span><span className="admin-section-note">Search & filter</span><span className="admin-section-note">Permissions</span><span className="admin-section-note">Activity history</span><span className="admin-section-note">Reports</span><span className="admin-section-note">Notifications</span></div></Section></>}

export default async function AdminModulePage({params}:{params:Promise<{module:string}>}){const {module}=await params;const item=adminModules.find(m=>m.slug===module);if(!item||["pages","themes","plugins"].includes(module))return notFound();let body:React.ReactNode;if(module==="roles")body=<Roles/>;else if(module==="system")body=await System();else if(module==="users")body=await Users();else if(module==="members")body=await Members();else if(module==="audit-logs")body=await Audit();else if(module==="programs")body=await Programs();else if(module==="projects")body=await Projects();else if(module==="posts")body=await Posts();else if(module==="events")body=await Events();else if(module==="forms")body=await Forms();else if(module==="media")body=await Media();else if(module==="navigation")body=await Navigation();else if(module==="leadership")body=await Leadership();else if(module==="partners")body=await Partners();else if(module==="settings")body=await Settings();else if(module==="email")body=await Email();else if(module==="seo")body=await Seo();else if(module==="finance")body=<Finance/>;else if(module==="reports")body=<Reports/>;else if(module==="notifications")body=<Notifications/>;else body=<DefaultModule label={item.label}/>;return <main className="admin-content"><div className="admin-page-head"><div><span className="admin-breadcrumb">MWONET Admin / {item.group}</span><h1>{item.label}</h1><p>{item.description}</p></div><span className="admin-badge">Module</span></div><section className="admin-module-hero"><div><span className="admin-kicker">{item.group.toUpperCase()}</span><h2>{item.label}</h2><p>{item.description}</p></div><span className="admin-module-icon">{item.icon}</span></section>{body}</main>}
