import {notFound} from "next/navigation";
import {adminModules,permissionGroups} from "../../_data/admin";
import {db} from "../../_lib/db";
import {databaseHealth} from "../../_lib/cms";

export const dynamic="force-dynamic";
export function generateStaticParams(){return adminModules.filter(m=>!["pages","themes","plugins"].includes(m.slug)).map(m=>({module:m.slug}))}

function Roles(){return <div className="admin-permission-grid">{permissionGroups.map(g=><article className="admin-permission-group" key={g.name}><h3>{g.name}</h3><ul>{g.permissions.map(p=><li key={p}>{p}</li>)}</ul></article>)}</div>}

async function System(){const health=await databaseHealth();return <div className="admin-grid"><section className="admin-panel"><div className="admin-panel-head"><h2>Environment readiness</h2></div><div className="admin-config-list"><div className="admin-status-row"><span>Admin credentials</span><b className="admin-status-good">Configured at runtime</b></div><div className="admin-status-row"><span>PostgreSQL / Neon</span><b className={health.ok?"admin-status-good":"admin-status-pending"}>{health.ok?`Connected (${health.latency}ms)`:"Connection issue"}</b></div><div className="admin-status-row"><span>Prisma schema</span><b className="admin-status-good">Enabled</b></div><div className="admin-status-row"><span>Page revisions</span><b className="admin-status-good">Persistent</b></div><div className="admin-status-row"><span>Audit persistence</span><b className="admin-status-good">Persistent</b></div><div className="admin-status-row"><span>Media binary storage</span><b className="admin-status-pending">External provider pending</b></div></div></section><section className="admin-panel"><div className="admin-panel-head"><h2>Runtime configuration</h2></div><div className="admin-config-list"><code>MWONET_ADMIN_EMAIL ✓</code><code>MWONET_ADMIN_PASSWORD ✓</code><code>MWONET_ADMIN_SESSION_SECRET ✓</code><code>DATABASE_URL ✓</code></div><p className="admin-section-note">Secrets remain in Vercel environment variables and are never displayed from the application.</p></section></div>}

async function Users(){const users=await db.user.findMany({orderBy:{createdAt:"desc"},take:100,include:{roles:{include:{role:true}},member:true}});return <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Member</th><th>Last sign-in</th></tr></thead><tbody>{users.length?users.map(u=><tr key={u.id}><td><strong>{u.name||"Unnamed user"}</strong><small>{u.email}</small></td><td>{u.roles.map(r=>r.role.name).join(", ")||"—"}</td><td><span className="admin-badge">{u.status}</span></td><td>{u.member?.memberNumber||u.member?.status||"—"}</td><td>{u.lastLoginAt?u.lastLoginAt.toLocaleString("en-KE"):"Never"}</td></tr>):<tr><td colSpan={5}><div className="admin-empty"><strong>No users yet</strong>User accounts will appear here as authentication and registration flows go live.</div></td></tr>}</tbody></table></div>}

async function Members(){const members=await db.memberProfile.findMany({orderBy:{joinedAt:"desc"},take:100,include:{user:true}});return <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Member</th><th>Number</th><th>County</th><th>Status</th><th>Fees</th></tr></thead><tbody>{members.length?members.map(m=><tr key={m.id}><td><strong>{m.user.name||"Unnamed"}</strong><small>{m.user.email}{m.phone?` · ${m.phone}`:""}</small></td><td>{m.memberNumber||"Pending"}</td><td>{m.county||"—"}</td><td><span className="admin-badge">{m.status}</span></td><td><small>Registration KSh {m.registrationFee?.toString()||"—"}<br/>Monthly KSh {m.monthlyFee?.toString()||"—"}</small></td></tr>):<tr><td colSpan={5}><div className="admin-empty"><strong>No member records yet</strong>Approved and pending membership records will appear here.</div></td></tr>}</tbody></table></div>}

async function Audit(){const logs=await db.auditLog.findMany({orderBy:{createdAt:"desc"},take:150,include:{actor:true}});return <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Resource</th><th>ID</th></tr></thead><tbody>{logs.length?logs.map(l=><tr key={l.id}><td>{l.createdAt.toLocaleString("en-KE")}</td><td>{l.actor?.email||"System"}</td><td><strong>{l.action}</strong></td><td>{l.resource}</td><td><code>{l.resourceId||"—"}</code></td></tr>):<tr><td colSpan={5}><div className="admin-empty"><strong>No audit records yet</strong>CMS edits and future administrative actions will be recorded here.</div></td></tr>}</tbody></table></div>}

async function Programs(){const rows=await db.program.findMany({orderBy:{title:"asc"},include:{_count:{select:{projects:true}}}});return <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Program</th><th>Slug</th><th>Projects</th><th>Summary</th></tr></thead><tbody>{rows.length?rows.map(x=><tr key={x.id}><td><strong>{x.title}</strong></td><td><code>{x.slug}</code></td><td>{x._count.projects}</td><td>{x.summary||"—"}</td></tr>):<tr><td colSpan={4}><div className="admin-empty"><strong>No database programs yet</strong>The public focus areas remain live; this workspace is ready for structured program records.</div></td></tr>}</tbody></table></div>}

async function Projects(){const rows=await db.project.findMany({orderBy:{title:"asc"},include:{program:true}});return <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Project</th><th>Program</th><th>Status</th><th>Location</th><th>Dates</th></tr></thead><tbody>{rows.length?rows.map(x=><tr key={x.id}><td><strong>{x.title}</strong><small>{x.slug}</small></td><td>{x.program?.title||"—"}</td><td><span className="admin-badge">{x.status}</span></td><td>{x.location||"—"}</td><td>{x.startDate?.toLocaleDateString("en-KE")||"—"}{x.endDate?` → ${x.endDate.toLocaleDateString("en-KE")}`:""}</td></tr>):<tr><td colSpan={5}><div className="admin-empty"><strong>No projects yet</strong>Projects can be structured here with program, status, dates, location and evidence.</div></td></tr>}</tbody></table></div>}

async function Posts(){const rows=await db.post.findMany({orderBy:{createdAt:"desc"},take:100});return <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Title</th><th>Status</th><th>Published</th><th>Updated</th></tr></thead><tbody>{rows.length?rows.map(x=><tr key={x.id}><td><strong>{x.title}</strong><small>{x.slug}</small></td><td><span className="admin-badge">{x.status}</span></td><td>{x.publishedAt?.toLocaleString("en-KE")||"—"}</td><td>{x.updatedAt.toLocaleString("en-KE")}</td></tr>):<tr><td colSpan={4}><div className="admin-empty"><strong>No news posts yet</strong>Draft and published stories will appear here.</div></td></tr>}</tbody></table></div>}

async function Events(){const rows=await db.event.findMany({orderBy:{startsAt:"desc"},take:100});return <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Event</th><th>Status</th><th>Venue</th><th>Starts</th><th>Ends</th></tr></thead><tbody>{rows.length?rows.map(x=><tr key={x.id}><td><strong>{x.title}</strong><small>{x.slug}</small></td><td><span className="admin-badge">{x.status}</span></td><td>{x.venue||"—"}</td><td>{x.startsAt.toLocaleString("en-KE")}</td><td>{x.endsAt?.toLocaleString("en-KE")||"—"}</td></tr>):<tr><td colSpan={5}><div className="admin-empty"><strong>No events yet</strong>Event scheduling and registrations will be managed here.</div></td></tr>}</tbody></table></div>}

async function Forms(){const rows=await db.form.findMany({orderBy:{name:"asc"},include:{_count:{select:{submissions:true}}}});return <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Form</th><th>Key</th><th>Submissions</th></tr></thead><tbody>{rows.length?rows.map(x=><tr key={x.id}><td><strong>{x.name}</strong></td><td><code>{x.key}</code></td><td>{x._count.submissions}</td></tr>):<tr><td colSpan={3}><div className="admin-empty"><strong>No forms yet</strong>Contact, volunteer, partner and application forms will be managed here.</div></td></tr>}</tbody></table></div>}

function DefaultModule({label}:{label:string}){return <><div className="admin-panel"><div className="admin-panel-head"><h2>{label} workspace</h2></div><div className="admin-empty"><strong>Management workspace ready</strong>This area is prepared for structured records, approvals, filters, reporting and controlled actions.</div></div><div className="admin-panel"><div className="admin-panel-head"><h2>Management controls</h2></div><div className="admin-quick-grid"><span className="admin-section-note">Create & edit</span><span className="admin-section-note">Draft & publish</span><span className="admin-section-note">Search & filter</span><span className="admin-section-note">Permissions</span><span className="admin-section-note">Activity history</span><span className="admin-section-note">Export & reports</span><span className="admin-section-note">Bulk actions</span><span className="admin-section-note">Notifications</span></div></div></>}

export default async function AdminModulePage({params}:{params:Promise<{module:string}>}){const {module}=await params;const item=adminModules.find(m=>m.slug===module);if(!item||["pages","themes","plugins"].includes(module))return notFound();let body:React.ReactNode;if(module==="roles")body=<Roles/>;else if(module==="system")body=await System();else if(module==="users")body=await Users();else if(module==="members")body=await Members();else if(module==="audit-logs")body=await Audit();else if(module==="programs")body=await Programs();else if(module==="projects")body=await Projects();else if(module==="posts")body=await Posts();else if(module==="events")body=await Events();else if(module==="forms")body=await Forms();else body=<DefaultModule label={item.label}/>;return <main className="admin-content"><div className="admin-page-head"><div><span className="admin-breadcrumb">MWONET Admin / {item.group}</span><h1>{item.label}</h1><p>{item.description}</p></div><span className="admin-badge">{["users","members","audit-logs","programs","projects","posts","events","forms","system"].includes(module)?"Database live":"Workspace"}</span></div><section className="admin-module-hero"><div><span className="admin-kicker">{item.group.toUpperCase()}</span><h2>{item.label}</h2><p>{item.description}</p></div><span className="admin-module-icon">{item.icon}</span></section>{body}</main>}
