import {notFound} from "next/navigation";
import {adminModules,permissionGroups} from "../../_data/admin";

export function generateStaticParams(){return adminModules.filter(m=>!["pages","themes","plugins"].includes(m.slug)).map(m=>({module:m.slug}))}

function Roles(){return <div className="admin-permission-grid">{permissionGroups.map(g=><article className="admin-permission-group" key={g.name}><h3>{g.name}</h3><ul>{g.permissions.map(p=><li key={p}>{p}</li>)}</ul></article>)}</div>}
function System(){return <div className="admin-grid"><section className="admin-panel"><div className="admin-panel-head"><h2>Environment readiness</h2></div><div className="admin-config-list"><div className="admin-status-row"><span>Admin credentials</span><b className="admin-status-good">Configured at runtime</b></div><div className="admin-status-row"><span>PostgreSQL / Neon</span><b className="admin-status-pending">Next phase</b></div><div className="admin-status-row"><span>Prisma schema</span><b className="admin-status-pending">Next phase</b></div><div className="admin-status-row"><span>Media storage</span><b className="admin-status-pending">Provider selection pending</b></div><div className="admin-status-row"><span>Audit persistence</span><b className="admin-status-pending">Requires database</b></div></div></section><section className="admin-panel"><div className="admin-panel-head"><h2>Required Vercel variables</h2></div><div className="admin-config-list"><code>MWONET_ADMIN_EMAIL</code><code>MWONET_ADMIN_PASSWORD</code><code>MWONET_ADMIN_SESSION_SECRET</code></div><p className="admin-section-note">Do not put real credentials in GitHub. Configure them only in Vercel environment variables.</p></section></div>}
function Users(){return <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Last sign-in</th><th>Access</th></tr></thead><tbody><tr><td><strong>Primary Administrator</strong><small>Environment-backed admin account</small></td><td>Super Admin</td><td><span className="admin-badge">Active</span></td><td>Current session</td><td>Full platform</td></tr><tr><td colSpan={5}><div className="admin-empty"><strong>Database-backed users come next</strong>When PostgreSQL authentication is connected, registered users and staff accounts will appear here with status, roles and sign-in activity.</div></td></tr></tbody></table></div>}
function Audit(){return <div className="admin-empty"><strong>Audit trail foundation is ready</strong>Persistent records such as “who changed what and when” require the database layer. The final model will record actor, action, resource, before/after data, timestamp and IP/session metadata.</div>}
function DefaultModule({label}:{label:string}){return <><div className="admin-panel"><div className="admin-panel-head"><h2>{label} workspace</h2></div><div className="admin-empty"><strong>Module architecture created</strong>This area is ready to receive its database models, forms, filters, approvals and reporting workflow without changing the admin navigation structure.</div></div><div className="admin-panel"><div className="admin-panel-head"><h2>Planned management controls</h2></div><div className="admin-quick-grid"><span className="admin-section-note">Create & edit</span><span className="admin-section-note">Draft & publish</span><span className="admin-section-note">Search & filter</span><span className="admin-section-note">Permissions</span><span className="admin-section-note">Activity history</span><span className="admin-section-note">Export & reports</span><span className="admin-section-note">Bulk actions</span><span className="admin-section-note">Notifications</span></div></div></>}

export default async function AdminModulePage({params}:{params:Promise<{module:string}>}){const {module}=await params;const item=adminModules.find(m=>m.slug===module);if(!item||["pages","themes","plugins"].includes(module))return notFound();return <main className="admin-content"><div className="admin-page-head"><div><span className="admin-breadcrumb">MWONET Admin / {item.group}</span><h1>{item.label}</h1><p>{item.description}</p></div><button className="admin-primary" type="button">New {item.label.replace(/s$/,'')}</button></div><section className="admin-module-hero"><div><span className="admin-kicker">{item.group.toUpperCase()}</span><h2>{item.label}</h2><p>{item.description}</p></div><span className="admin-module-icon">{item.icon}</span></section>{module==="roles"?<Roles/>:module==="system"?<System/>:module==="users"?<Users/>:module==="audit-logs"?<Audit/>:<DefaultModule label={item.label}/>}</main>}
