import Link from "next/link";
import {getPublicCmsPage} from "../_lib/public-cms";
import {getSiteConfig} from "../_lib/site-config";
import CmsPageRenderer from "../components/CmsPageRenderer";
import PageHero from "../components/PageHero";
import {images} from "../data/site";

export const dynamic="force-dynamic";
export default async function Contact(){
 const [cms,config]=await Promise.all([getPublicCmsPage("contact"),getSiteConfig()]);
 const socials=[["Facebook",config["social.facebook"]],["Instagram",config["social.instagram"]],["YouTube",config["social.youtube"]],["LinkedIn",config["social.linkedin"]]].filter((x):x is [string,string]=>Boolean(x[1]));
 return <>{cms?<CmsPageRenderer title={cms.title} description={cms.description} blocks={cms.blocks}/>:<PageHero eyebrow="Contact" title="Connect with MWONET in Bungoma County." text="For partnerships, programs, membership, volunteering and general enquiries, use MWONET's official communication channels." image={images.mountain}/>}
 <section className="section"><div className="container contact-pro-grid"><div><p className="eyebrow">OFFICIAL CHANNELS</p><h2>Talk to the network.</h2><div className="contact-lines"><a href={"mailto:"+config["organization.email"]}><small>GENERAL EMAIL</small><strong>{config["organization.email"]}</strong></a>{config["organization.secondaryEmail"]&&<a href={"mailto:"+config["organization.secondaryEmail"]}><small>ADDITIONAL EMAIL</small><strong>{config["organization.secondaryEmail"]}</strong></a>}{config["organization.phone"]&&<a href={"tel:"+config["organization.phone"]}><small>PHONE</small><strong>{config["organization.phone"]}</strong></a>}<div><small>WEBSITE</small><strong>www.mwonet.org</strong></div><div><small>HEADQUARTERS</small><strong>{config["organization.address"]}</strong></div></div><p className="notice">Incoming messages sent to the official MWONET domain are received through secure email routing. Authenticated sending as @mwonet.org requires an approved outbound mailbox/SMTP service.</p></div><div className="interest-form"><p className="eyebrow">SEND AN ENQUIRY</p><h2>Use the secure MWONET contact form.</h2><p>Your message is stored inside the MWONET administration system so an authorized officer can review it.</p><Link className="button primary" href="/forms/contact">Open contact form</Link><a className="button" href={"mailto:"+config["organization.email"]}>Or send email</a></div></div></section>
 <section className="section tint"><div className="container"><div className="section-head"><div><p className="eyebrow">OUR BASE</p><h2>Kapkatenyi · Kopsiro · Bungoma.</h2></div><p>{config["organization.address"]}</p></div>{config["organization.mapUrl"]?<a className="map-placeholder" href={config["organization.mapUrl"]} target="_blank" rel="noreferrer"><span>OPEN MWONET LOCATION IN MAPS ↗</span></a>:<div className="map-placeholder"><span>MAP LINK CAN BE ADDED IN ADMIN → SITE SETTINGS</span></div>}</div></section>
 <section className="section"><div className="container"><p className="eyebrow">SOCIAL MEDIA</p><h2>Follow the work.</h2>{socials.length?<div className="social-grid">{socials.map(([name,url])=><a key={name} href={url} target="_blank" rel="noreferrer">{name}<br/><small>Official MWONET channel ↗</small></a>)}</div>:<div className="notice">Official social-media links have not yet been supplied. They can be added at any time from Admin → Site Settings without changing website code.</div>}</div></section></>
}
