import type {ReactNode} from "react";import {notFound} from "next/navigation";import PageHero from "../../components/PageHero";import {images} from "../../data/site";import {constitution} from "../../data/constitution";
const sections:{[k:string]:{title:string,text:string,body:ReactNode}}={
 history:{title:"Identity & Location",text:"MWONET’s official name and physical base are established in Article 1 of the constitution.",body:<><p className="big-copy">The NGO is formally named <strong>Maanisha Western Organization Network (MWONET)</strong>.</p><p>Its official headquarters and physical office are stated as <strong>Kapkatenyi, Kopsiro Sub-County, Bungoma County, Kenya</strong>. A fuller historical narrative—formation date, founders, milestones and early community activities—has not yet been supplied in the constitution and should be added only from an approved organization profile.</p></>},
 vision:{title:"Our Vision",text:"The future MWONET is working to help create.",body:<p className="big-copy">{constitution.vision}</p>},
 mission:{title:"Our Mission",text:"The organization’s constitutional purpose and approach.",body:<p className="big-copy">{constitution.mission}</p>},
 objectives:{title:"Our Objectives",text:"Four constitutional pillars guide MWONET’s programs and partnerships.",body:<div className="objective-grid">{constitution.objectives.map((o,i)=><article className="objective-card" key={o.title}><span>{o.icon}</span><small>OBJECTIVE {String(i+1).padStart(2,"0")}</small><h3>{o.title}</h3><p>{o.text}</p></article>)}</div>},
 "core-values":{title:"Our Core Values",text:"Five principles define how MWONET intends to work.",body:<div className="value-grid">{constitution.values.map((v,i)=><article className="value-card" key={v.name}><span>{String(i+1).padStart(2,"0")}</span><h3>{v.name}</h3><p>{v.text}</p></article>)}</div>}
};
export function generateStaticParams(){return Object.keys(sections).map(slug=>({slug}))}
export default async function AboutDetail({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const d=sections[slug];if(!d)return notFound();return <><PageHero eyebrow="About MWONET" title={d.title} text={d.text} image={slug==="history"?images.mountain:images.community}/><section className="section"><div className="container">{d.body}</div></section></>}
