import Link from "next/link";
import {adminModules} from "../_data/admin";
import {db} from "../_lib/db";
import {databaseHealth,ensureCorePages,ensureSystemCatalog} from "../_lib/cms";

export const dynamic="force-dynamic";

export default async function AdminDashboard(){
 await Promise.all([ensureCorePages(),ensureSystemCatalog()]);
 const health=await databaseHealth();
 const [pages,members,users,projects,events,posts,media,partners,leaders,audits]=await Promise.all([
  db.page.count(),db.memberProfile.count(),db.user.count(),db.project.count(),db.event.count(),db.post.count(),db.mediaAsset.count(),db.partner.count(),db.leadershipProfile.count(),db.auditLog.findMany({orderBy:{createdAt:"desc"},take:8,include:{actor:true}})
 ]);
 const groups=[...new Set(adminModules.map(m=>m.group))];
 return <main className="admin-content"><div className="admin-page-head"><div><span className="admin-breadcrumb">MWONET / Administration</span><h1>Control Centre</h1><p>A WordPress-inspired, MWONET-specific administration platform for content, people, programs, projects, governance, communications, reporting and system control.</p></div><div><Link className="admin-primary" href="/admin/pages">Edit website</Link></div></div>
 <section className="admin-stat-grid"><article className="admin-stat"><small>MANAGED PAGES</small><strong>{pages}</strong><span>{posts} news posts · {media} media</span></article><article className="admin-stat"><small>PEOPLE</small><strong>{members}</strong><span>{users} users · {leaders} leaders</span></article><article className="admin-stat"><small>PROGRAM DELIVERY</small><strong>{projects}</strong><span>{events} events · {partners} partners</span></article><article className="admin-stat"><small>DATABASE</small><strong>{health.ok?"Live":"Check"}</strong><span>{health.ok?`${health.latency}ms response`:"Connection issue"}</span></article></section>
 <div className="admin-grid"><div>{groups.map(group=><section className="admin-panel" key={group}><div className="admin-panel-head"><h2>{group}</h2><span className="admin-badge">{adminModules.filter(m=>m.group===group).length} modules</span></div><div className="admin-apps">{adminModules.filter(m=>m.group===group).map(m=><Link className="admin-app-card" key={m.slug} href={`/admin/${m.slug}`}><span className="admin-app-icon">{m.icon}</span><h3>{m.label}</h3><p>{m.description}</p></Link>)}</div></section>)}<section className="admin-panel"><div className="admin-panel-head"><h2>Quick actions</h2></div><div className="admin-quick-grid"><Link href="/admin/pages">Edit a page</Link><Link href="/admin/posts">Create news</Link><Link href="/admin/events">Add event</Link><Link href="/admin/media">Add media</Link><Link href="/admin/members">Review members</Link><Link href="/admin/projects">Create project</Link><Link href="/admin/leadership">Leadership</Link><Link href="/admin/reports">Reports</Link></div></section></div>
 <aside><section className="admin-panel"><div className="admin-panel-head"><h2>Platform status</h2></div><div className="admin-status-list"><div className="admin-status-row"><span>Public website</span><b className="admin-status-good">Online</b></div><div className="admin-status-row"><span>Admin authentication</span><b className="admin-status-good">Protected</b></div><div className="admin-status-row"><span>PostgreSQL / Prisma</span><b className={health.ok?"admin-status-good":"admin-status-pending"}>{health.ok?"Connected":"Check"}</b></div><div className="admin-status-row"><span>Page revisions</span><b className="admin-status-good">Enabled</b></div><div className="admin-status-row"><span>Audit persistence</span><b className="admin-status-good">Enabled</b></div><div className="admin-status-row"><span>Theme / plugin engine</span><b className="admin-status-good">Controlled</b></div><div className="admin-status-row"><span>Email receiving</span><b className="admin-status-good">Live</b></div><div className="admin-status-row"><span>Email sending</span><b className="admin-status-pending">Pending mailbox</b></div></div></section>
 <section className="admin-panel"><div className="admin-panel-head"><h2>Recent activity</h2><Link href="/admin/audit-logs">View all →</Link></div><div className="admin-activity">{audits.length?audits.map((a,i)=><article key={a.id}><i>{i+1}</i><div><h4>{a.action}</h4><p>{a.actor?.email||"System"} · {a.resource} · {a.createdAt.toLocaleString("en-KE")}</p></div></article>):<div className="admin-empty"><strong>No database activity yet</strong>Actions performed through the CMS will appear here.</div>}</div></section><section className="admin-panel"><div className="admin-panel-head"><h2>Operating principles</h2></div><div className="admin-config-list"><span className="admin-section-note">Verified information only for leadership and constitutional data.</span><span className="admin-section-note">No paid integration is activated without approval.</span><span className="admin-section-note">Sensitive actions should remain auditable and role-controlled.</span></div></section></aside></div></main>}
