import Link from "next/link";
import {adminModules} from "../_data/admin";
import {db} from "../_lib/db";
import {databaseHealth,ensureCorePages,ensureSystemCatalog} from "../_lib/cms";

export const dynamic="force-dynamic";

const featured=["pages","media","members","programs","projects","themes","plugins","audit-logs"].map(slug=>adminModules.find(m=>m.slug===slug)!).filter(Boolean);

export default async function AdminDashboard(){
 await Promise.all([ensureCorePages(),ensureSystemCatalog()]);
 const health=await databaseHealth();
 const [pages,members,users,projects,events,posts,audits]=await Promise.all([
  db.page.count(),db.memberProfile.count(),db.user.count(),db.project.count(),db.event.count(),db.post.count(),db.auditLog.findMany({orderBy:{createdAt:"desc"},take:6,include:{actor:true}})
 ]);
 return <main className="admin-content"><div className="admin-page-head"><div><span className="admin-breadcrumb">MWONET / Administration</span><h1>Control Centre</h1><p>Manage the public website, people, programs, content, settings and system access from one secure workspace.</p></div><div><Link className="admin-primary" href="/admin/pages">Edit website</Link></div></div>
 <section className="admin-stat-grid"><article className="admin-stat"><small>MANAGED PAGES</small><strong>{pages}</strong><span>Database-backed CMS pages</span></article><article className="admin-stat"><small>MEMBERS</small><strong>{members}</strong><span>{users} total user accounts</span></article><article className="admin-stat"><small>PROJECT ACTIVITY</small><strong>{projects}</strong><span>{events} events · {posts} posts</span></article><article className="admin-stat"><small>DATABASE</small><strong>{health.ok?"Live":"Check"}</strong><span>{health.ok?`${health.latency}ms response`:"Connection issue"}</span></article></section>
 <div className="admin-grid"><div><section className="admin-panel"><div className="admin-panel-head"><h2>Apps home</h2><Link href="/admin/system">System status →</Link></div><div className="admin-apps">{featured.map(m=><Link className="admin-app-card" key={m.slug} href={`/admin/${m.slug}`}><span className="admin-app-icon">{m.icon}</span><h3>{m.label}</h3><p>{m.description}</p></Link>)}</div></section><section className="admin-panel"><div className="admin-panel-head"><h2>Quick actions</h2></div><div className="admin-quick-grid"><Link href="/admin/pages">Edit a page</Link><Link href="/admin/posts">Manage news</Link><Link href="/admin/events">Manage events</Link><Link href="/admin/media">Media library</Link><Link href="/admin/members">Review members</Link><Link href="/admin/programs">Programs</Link><Link href="/admin/themes">Themes</Link><Link href="/admin/audit-logs">Activity log</Link></div></section></div>
 <aside><section className="admin-panel"><div className="admin-panel-head"><h2>Platform status</h2></div><div className="admin-status-list"><div className="admin-status-row"><span>Public website</span><b className="admin-status-good">Online</b></div><div className="admin-status-row"><span>Admin authentication</span><b className="admin-status-good">Protected</b></div><div className="admin-status-row"><span>PostgreSQL / Prisma</span><b className={health.ok?"admin-status-good":"admin-status-pending"}>{health.ok?"Connected":"Check"}</b></div><div className="admin-status-row"><span>Page revisions</span><b className="admin-status-good">Enabled</b></div><div className="admin-status-row"><span>Audit persistence</span><b className="admin-status-good">Enabled</b></div><div className="admin-status-row"><span>Theme / plugin engine</span><b className="admin-status-good">Catalog initialized</b></div></div></section>
 <section className="admin-panel"><div className="admin-panel-head"><h2>Recent activity</h2><Link href="/admin/audit-logs">View all →</Link></div><div className="admin-activity">{audits.length?audits.map((a,i)=><article key={a.id}><i>{i+1}</i><div><h4>{a.action}</h4><p>{a.actor?.email||"System"} · {a.resource} · {a.createdAt.toLocaleString("en-KE")}</p></div></article>):<div className="admin-empty"><strong>No database activity yet</strong>Actions performed through the CMS will appear here.</div>}</div></section></aside></div></main>}
