import Link from "next/link";
import {adminModules} from "../_data/admin";
import {db} from "../_lib/db";
import {databaseHealth,ensureCorePages,ensureSystemCatalog} from "../_lib/cms";
import {requireAdmin} from "../_lib/auth";
import {canAccess,getUserAccess,isModulePluginEnabled,modulePermission} from "../_lib/access";

export const dynamic="force-dynamic";

export default async function AdminDashboard(){
 const session=await requireAdmin();await Promise.all([ensureCorePages(),ensureSystemCatalog()]);const access=await getUserAccess(session.email);const health=await databaseHealth();
 const [pages,members,users,projects,events,posts,media,partners,leaders,audits]=await Promise.all([db.page.count(),db.memberProfile.count(),db.user.count(),db.project.count(),db.event.count(),db.post.count(),db.mediaAsset.count(),db.partner.count(),db.leadershipProfile.count(),db.auditLog.findMany({orderBy:{createdAt:"desc"},take:8,include:{actor:true}})]);
 const permitted=adminModules.filter(m=>canAccess(access.permissions,access.isSuperAdmin,modulePermission[m.slug]));const pluginState=await Promise.all(permitted.map(async m=>[m.slug,await isModulePluginEnabled(m.slug)] as const));const flags=new Map(pluginState);const modules=permitted.filter(m=>access.isSuperAdmin||flags.get(m.slug)!==false);const groups=[...new Set(modules.map(m=>m.group))];const quick=modules.filter(m=>["pages","posts","events","media","members","projects","leadership","reports"].includes(m.slug)).slice(0,8);
 return <main className="admin-content"><div className="admin-page-head"><div><span className="admin-breadcrumb">MWONET / Administration</span><h1>Control Centre</h1><p>Your dashboard only shows modules permitted for your assigned role. Super Admin controls owner-level security, themes, plugins and destructive actions.</p></div>{canAccess(access.permissions,access.isSuperAdmin,"edit_pages")&&<div><Link className="admin-primary" href="/admin/pages">Edit website</Link></div>}</div>
 <section className="admin-stat-grid"><article className="admin-stat"><small>MANAGED PAGES</small><strong>{pages}</strong><span>{posts} news posts · {media} media</span></article><article className="admin-stat"><small>PEOPLE</small><strong>{members}</strong><span>{users} users · {leaders} leaders</span></article><article className="admin-stat"><small>PROGRAM DELIVERY</small><strong>{projects}</strong><span>{events} events · {partners} partners</span></article><article className="admin-stat"><small>DATABASE</small><strong>{health.ok?"Live":"Check"}</strong><span>{health.ok?`${health.latency}ms response`:"Connection issue"}</span></article></section>
 <div className="admin-grid"><div>{groups.map(group=><section className="admin-panel" key={group}><div className="admin-panel-head"><h2>{group}</h2><span className="admin-badge">{modules.filter(m=>m.group===group).length} modules</span></div><div className="admin-apps">{modules.filter(m=>m.group===group).map(m=><Link className="admin-app-card" key={m.slug} href={`/admin/${m.slug}`}><span className="admin-app-icon">{m.icon}</span><h3>{m.label}</h3><p>{m.description}</p></Link>)}</div></section>)}{quick.length>0&&<section className="admin-panel"><div className="admin-panel-head"><h2>Quick actions</h2></div><div className="admin-quick-grid">{quick.map(m=><Link key={m.slug} href={`/admin/${m.slug}`}>{m.label}</Link>)}</div></section>}</div>
 <aside><section className="admin-panel"><div className="admin-panel-head"><h2>Your access</h2></div><div className="admin-config-list"><span className="admin-section-note"><strong>Roles:</strong> {access.roles.join(", ")||"No assigned role"}</span><span className="admin-section-note"><strong>Modules visible:</strong> {modules.length}</span><span className="admin-section-note">Access is controlled by database roles and permissions, not by hiding links only.</span></div></section><section className="admin-panel"><div className="admin-panel-head"><h2>Platform status</h2></div><div className="admin-status-list"><div className="admin-status-row"><span>Public website</span><b className="admin-status-good">Online</b></div><div className="admin-status-row"><span>Admin authentication</span><b className="admin-status-good">Protected</b></div><div className="admin-status-row"><span>PostgreSQL / Prisma</span><b className={health.ok?"admin-status-good":"admin-status-pending"}>{health.ok?"Connected":"Check"}</b></div><div className="admin-status-row"><span>Page revisions</span><b className="admin-status-good">Enabled</b></div><div className="admin-status-row"><span>Audit persistence</span><b className="admin-status-good">Enabled</b></div><div className="admin-status-row"><span>Theme / plugin engine</span><b className="admin-status-good">Controlled</b></div><div className="admin-status-row"><span>Email receiving</span><b className="admin-status-good">Live</b></div><div className="admin-status-row"><span>Email sending</span><b className="admin-status-pending">External mailbox optional</b></div></div></section>
 {canAccess(access.permissions,access.isSuperAdmin,"view_audit_logs")&&<section className="admin-panel"><div className="admin-panel-head"><h2>Recent activity</h2><Link href="/admin/audit-logs">View all →</Link></div><div className="admin-activity">{audits.length?audits.map((a,i)=><article key={a.id}><i>{i+1}</i><div><h4>{a.action}</h4><p>{a.actor?.email||"System"} · {a.resource} · {a.createdAt.toLocaleString("en-KE")}</p></div></article>):<div className="admin-empty"><strong>No database activity yet</strong>Actions performed through the CMS will appear here.</div>}</div></section>}<section className="admin-panel"><div className="admin-panel-head"><h2>Operating principles</h2></div><div className="admin-config-list"><span className="admin-section-note">Use verified information for leadership, constitution, payments and partnerships.</span><span className="admin-section-note">Do not place passwords or private credentials in content or Site Settings.</span><span className="admin-section-note">Use archive/deactivate before permanent deletion; destructive actions remain Super Admin controlled.</span></div></section></aside></div></main>}
