"use server";
import {revalidatePath} from "next/cache";
import {redirect} from "next/navigation";
import {db} from "../_lib/db";
import {getAdminSession} from "../_lib/auth";
import {requirePermission,getUserAccess} from "../_lib/access";

function v(fd:FormData,key:string){return String(fd.get(key)||"").trim()}
function slugify(s:string){return s.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}
async function guard(permission:string){const s=await getAdminSession();if(!s)redirect("/admin/login");return requirePermission(s.email,permission)}
async function audit(actorId:string|undefined,action:string,resource:string,id:string,before:unknown,after:unknown){await db.auditLog.create({data:{actorId,action,resource,resourceId:id,before:before as never,after:after as never}})}
async function owner(){const s=await getAdminSession();if(!s)redirect("/admin/login");const a=await getUserAccess(s.email);if(!a.isSuperAdmin)throw new Error("Only Super Admin can permanently delete records.");return a}

export async function updateProgram(fd:FormData){const a=await guard("manage_programs");const id=v(fd,"id"),title=v(fd,"title");if(!id||!title)return;const before=await db.program.findUnique({where:{id}});if(!before)return;const row=await db.program.update({where:{id},data:{title,slug:slugify(v(fd,"slug")||title),summary:v(fd,"summary")||null,content:{body:v(fd,"content")}}});await audit(a.user?.id,"program.update","Program",id,before,row);revalidatePath("/admin/programs");redirect("/admin/programs")}
export async function updateProject(fd:FormData){const a=await guard("manage_projects");const id=v(fd,"id"),title=v(fd,"title");if(!id||!title)return;const before=await db.project.findUnique({where:{id}});if(!before)return;const start=v(fd,"startDate"),end=v(fd,"endDate"),programId=v(fd,"programId");const status=v(fd,"status") as "PLANNING"|"ACTIVE"|"PAUSED"|"COMPLETED"|"ARCHIVED";const row=await db.project.update({where:{id},data:{title,slug:slugify(v(fd,"slug")||title),summary:v(fd,"summary")||null,location:v(fd,"location")||null,programId:programId||null,startDate:start?new Date(start):null,endDate:end?new Date(end):null,status:status||before.status,content:{body:v(fd,"content")}}});await audit(a.user?.id,"project.update","Project",id,before,row);revalidatePath("/admin/projects");redirect("/admin/projects")}
export async function updatePost(fd:FormData){const a=await guard("manage_posts");const id=v(fd,"id"),title=v(fd,"title");if(!id||!title)return;const before=await db.post.findUnique({where:{id}});if(!before)return;const status=v(fd,"status") as "DRAFT"|"REVIEW"|"PUBLISHED"|"SCHEDULED"|"ARCHIVED";const row=await db.post.update({where:{id},data:{title,slug:slugify(v(fd,"slug")||title),excerpt:v(fd,"excerpt")||null,content:{body:v(fd,"content")},status:status||before.status,publishedAt:status==="PUBLISHED"?(before.publishedAt||new Date()):before.publishedAt}});await audit(a.user?.id,"post.update","Post",id,before,row);revalidatePath("/admin/posts");revalidatePath("/news");redirect("/admin/posts")}
export async function updateEvent(fd:FormData){const a=await guard("manage_events");const id=v(fd,"id"),title=v(fd,"title"),starts=v(fd,"startsAt");if(!id||!title||!starts)return;const before=await db.event.findUnique({where:{id}});if(!before)return;const ends=v(fd,"endsAt"),status=v(fd,"status") as "DRAFT"|"REVIEW"|"PUBLISHED"|"SCHEDULED"|"ARCHIVED";const row=await db.event.update({where:{id},data:{title,slug:slugify(v(fd,"slug")||title),description:v(fd,"description")||null,venue:v(fd,"venue")||null,startsAt:new Date(starts),endsAt:ends?new Date(ends):null,status:status||before.status}});await audit(a.user?.id,"event.update","Event",id,before,row);revalidatePath("/admin/events");revalidatePath("/events");redirect("/admin/events")}
export async function updateLeader(fd:FormData){const a=await guard("manage_leadership");const id=v(fd,"id"),name=v(fd,"name"),role=v(fd,"role");if(!id||!name||!role)return;const before=await db.leadershipProfile.findUnique({where:{id}});if(!before)return;const row=await db.leadershipProfile.update({where:{id},data:{name,role,bio:v(fd,"bio")||null,photoUrl:v(fd,"photoUrl")||null,email:v(fd,"email")||null,phone:v(fd,"phone")||null,order:Number(v(fd,"order")||0),active:v(fd,"active")!=="false"}});await audit(a.user?.id,"leadership.update","LeadershipProfile",id,before,row);revalidatePath("/admin/leadership");revalidatePath("/leadership");redirect("/admin/leadership")}
export async function updatePartner(fd:FormData){const a=await guard("manage_partners");const id=v(fd,"id"),name=v(fd,"name");if(!id||!name)return;const before=await db.partner.findUnique({where:{id}});if(!before)return;const row=await db.partner.update({where:{id},data:{name,category:v(fd,"category")||null,website:v(fd,"website")||null,logoUrl:v(fd,"logoUrl")||null,description:v(fd,"description")||null,active:v(fd,"active")!=="false"}});await audit(a.user?.id,"partner.update","Partner",id,before,row);revalidatePath("/admin/partners");revalidatePath("/partners");redirect("/admin/partners")}
export async function updateNavigation(fd:FormData){const a=await guard("manage_navigation");const id=v(fd,"id"),label=v(fd,"label"),href=v(fd,"href");if(!id||!label||!href)return;const before=await db.navigationItem.findUnique({where:{id}});if(!before)return;const row=await db.navigationItem.update({where:{id},data:{label,href,location:v(fd,"location")||"header",order:Number(v(fd,"order")||0),visible:v(fd,"visible")!=="false"}});await audit(a.user?.id,"navigation.update","NavigationItem",id,before,row);revalidatePath("/admin/navigation");redirect("/admin/navigation")}
export async function updateFormDefinition(fd:FormData){const a=await guard("manage_forms");const id=v(fd,"id"),name=v(fd,"name");if(!id||!name)return;const before=await db.form.findUnique({where:{id}});if(!before)return;const fields=v(fd,"fields").split(",").map(x=>x.trim()).filter(Boolean);const row=await db.form.update({where:{id},data:{name,key:slugify(v(fd,"key")||name),schema:{fields}}});await audit(a.user?.id,"form.update","Form",id,before,row);revalidatePath("/admin/forms");redirect("/admin/forms")}
export async function deleteResource(fd:FormData){const a=await owner();const type=v(fd,"type"),id=v(fd,"id");if(!type||!id)return;
 if(type==="post"){const before=await db.post.findUnique({where:{id}});if(before){await db.post.delete({where:{id}});await audit(a.user?.id,"post.delete","Post",id,before,null)}}
 else if(type==="event"){const before=await db.event.findUnique({where:{id}});if(before){await db.event.delete({where:{id}});await audit(a.user?.id,"event.delete","Event",id,before,null)}}
 else if(type==="partner"){const before=await db.partner.findUnique({where:{id}});if(before){await db.partner.delete({where:{id}});await audit(a.user?.id,"partner.delete","Partner",id,before,null)}}
 else if(type==="leader"){const before=await db.leadershipProfile.findUnique({where:{id}});if(before){await db.leadershipProfile.delete({where:{id}});await audit(a.user?.id,"leadership.delete","LeadershipProfile",id,before,null)}}
 else return;
 revalidatePath("/admin/"+(type==="post"?"posts":type==="event"?"events":type==="leader"?"leadership":"partners"));
}
