import {db} from "../../_lib/db";
import {savePublicSettings} from "./actions";

export const dynamic="force-dynamic";
function read(row:{value:unknown}|undefined){const v=row?.value;return v&&typeof v==="object"&&!Array.isArray(v)?String((v as Record<string,unknown>).value||""):""}
export default async function SettingsPage(){
 const rows=await db.siteSetting.findMany();const map=new Map(rows.map(r=>[r.key,r]));
 return <main className="admin-content"><div className="admin-page-head"><div><span className="admin-breadcrumb">MWONET Admin / System</span><h1>Site Settings</h1><p>Manage official contact information, office location and social-media links used across the public website.</p></div><span className="admin-badge">Global settings</span></div>
 <section className="admin-panel"><div className="admin-panel-head"><h2>Organization identity & contact</h2></div><form action={savePublicSettings} className="admin-form admin-form-grid"><label>Public phone<input name="organization.phone" defaultValue={read(map.get("organization.phone"))} placeholder="+254..."/></label><label>General email<input type="email" name="organization.email" defaultValue={read(map.get("organization.email"))||"info@mwonet.org"}/></label><label>Secondary email<input type="email" name="organization.secondaryEmail" defaultValue={read(map.get("organization.secondaryEmail"))||"chesebe@mwonet.org"}/></label><label className="admin-span-2">Official physical address<textarea name="organization.address" rows={3} defaultValue={read(map.get("organization.address"))||"Kapkatenyi, Kopsiro Sub-County, Bungoma County, Kenya"}/></label><label className="admin-span-2">Google Maps / location URL<input name="organization.mapUrl" defaultValue={read(map.get("organization.mapUrl"))} placeholder="https://maps.google.com/..."/></label><h3 className="admin-span-2">Social media</h3><label>Facebook URL<input name="social.facebook" defaultValue={read(map.get("social.facebook"))} placeholder="https://facebook.com/..."/></label><label>Instagram URL<input name="social.instagram" defaultValue={read(map.get("social.instagram"))} placeholder="https://instagram.com/..."/></label><label>YouTube URL<input name="social.youtube" defaultValue={read(map.get("social.youtube"))} placeholder="https://youtube.com/@..."/></label><label>LinkedIn URL<input name="social.linkedin" defaultValue={read(map.get("social.linkedin"))} placeholder="https://linkedin.com/company/..."/></label><button className="admin-primary">Save public settings</button></form></section>
 <section className="admin-panel"><div className="admin-panel-head"><h2>What these settings control</h2></div><div className="admin-info-grid"><article><strong>Contact page</strong><p>Emails, phone, office address, map link and social-media links.</p></article><article><strong>Footer</strong><p>Official contact details and social channels shown on every page.</p></article><article><strong>Accuracy</strong><p>Only publish verified organizational information. Leave an unverified field blank rather than guessing.</p></article><article><strong>Security</strong><p>These settings are public information only. Never store passwords, API keys or private credentials here.</p></article></div></section></main>
}