import Link from "next/link";
import {getCmsPages,slugToPublicPath} from "../../_lib/cms";
import {archivePageAction,createPageAction,deletePageAction,duplicatePageAction} from "./actions";

export const dynamic="force-dynamic";

const statuses=["ALL","DRAFT","REVIEW","PUBLISHED","SCHEDULED","ARCHIVED"];

export default async function AdminPages({searchParams}:{searchParams:Promise<{q?:string;status?:string;deleted?:string;error?:string}>}){
 const sp=await searchParams;const q=(sp.q||"").trim().toLowerCase();const status=(sp.status||"ALL").toUpperCase();
 const all=await getCmsPages();const pages=all.filter(p=>(status==="ALL"||p.status===status)&&(!q||p.title.toLowerCase().includes(q)||p.slug.toLowerCase().includes(q)));
 const counts=Object.fromEntries(statuses.map(s=>[s,s==="ALL"?all.length:all.filter(p=>p.status===s).length]));
 return <main className="admin-content">
  <div className="admin-page-head"><div><span className="admin-breadcrumb">MWONET Admin / Website</span><h1>Pages</h1><p>Complete page management for the MWONET website: create, search, filter, edit, duplicate, archive, restore revisions, control SEO and publish content.</p></div><span className="admin-badge">{all.length} managed pages</span></div>
  {sp.deleted&&<div className="admin-success">Page deleted successfully.</div>}{sp.error==="slug"&&<div className="admin-alert error">That page URL already exists. Use a different slug.</div>}
  <section className="admin-panel"><div className="admin-panel-head"><h2>Create a new page</h2><span className="admin-badge">CMS</span></div><form action={createPageAction} className="admin-form"><div className="admin-form-grid"><label>Page title<input name="title" required placeholder="e.g. Climate Action Hub"/></label><label>URL slug<input name="slug" placeholder="climate-action-hub"/></label><label>Status<select name="status" defaultValue="DRAFT"><option value="DRAFT">Draft</option><option value="REVIEW">In review</option><option value="PUBLISHED">Published</option></select></label><label>Short description<input name="description" placeholder="A clear summary for search engines and visitors"/></label></div><div><button className="admin-primary" type="submit">Create page</button></div></form></section>
  <section className="admin-panel"><div className="admin-panel-head"><h2>Website pages</h2><span className="admin-badge">{pages.length} shown</span></div>
   <form className="admin-pages-filter" method="get"><input name="q" defaultValue={sp.q||""} placeholder="Search pages or URLs..."/><select name="status" defaultValue={status}>{statuses.map(s=><option key={s} value={s}>{s==="ALL"?`All (${counts[s]})`:`${s} (${counts[s]})`}</option>)}</select><button className="admin-secondary" type="submit">Filter</button><Link className="admin-secondary" href="/admin/pages">Reset</Link></form>
   <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Page</th><th>URL</th><th>Status</th><th>Content</th><th>Updated</th><th>Actions</th></tr></thead><tbody>{pages.length?pages.map(page=>{const path=slugToPublicPath(page.slug);const core=["home","about","contact","membership","governance","constitution","focus-areas","get-involved","leadership","media","events","mount-elgon","financial-model"].includes(page.slug);return <tr key={page.id}><td><strong>{page.title}</strong><small>{page.seoTitle||"SEO title not set"}</small></td><td><code>{path}</code></td><td><span className={`admin-badge ${page.status==="ARCHIVED"?"gray":page.status==="DRAFT"||page.status==="REVIEW"?"amber":""}`}>{page.status}</span></td><td><small>{page._count.blocks} blocks · {page._count.revisions} revisions</small></td><td>{page.updatedAt.toLocaleString("en-KE")}</td><td><div className="admin-inline-actions"><Link className="admin-action-link" href={`/admin/pages/${page.slug}`}>Edit</Link><Link className="admin-action-link" href={path} target="_blank">View ↗</Link><form action={duplicatePageAction}><input type="hidden" name="id" value={page.id}/><button className="admin-link-button" type="submit">Duplicate</button></form>{page.status!=="ARCHIVED"&&<form action={archivePageAction}><input type="hidden" name="id" value={page.id}/><button className="admin-link-button" type="submit">Archive</button></form>}{!core&&<form action={deletePageAction}><input type="hidden" name="id" value={page.id}/><button className="admin-link-button danger" type="submit">Delete</button></form>}</div></td></tr>}):<tr><td colSpan={6}><div className="admin-empty"><strong>No pages match this view</strong>Try another search or status filter.</div></td></tr>}</tbody></table></div>
  </section>
  <section className="admin-panel"><div className="admin-panel-head"><h2>Publishing workflow</h2></div><div className="admin-quick-grid"><span className="admin-section-note"><b>Draft</b><br/>Private working copy.</span><span className="admin-section-note"><b>Review</b><br/>Ready for internal checking.</span><span className="admin-section-note"><b>Published</b><br/>Approved public content.</span><span className="admin-section-note"><b>Scheduled</b><br/>Prepared for timed publication.</span></div></section>
 </main>
}
