import Link from "next/link";
import {db} from "../admin/_lib/db";
import {getSiteConfig} from "../_lib/site-config";

export default async function SiteFooter(){
 const config=await getSiteConfig();
 let footerLinks:{label:string;href:string}[]=[];
 try{footerLinks=await db.navigationItem.findMany({where:{location:"footer",visible:true},orderBy:{order:"asc"},select:{label:true,href:true}})}catch{}
 const socials=[["Facebook",config["social.facebook"]],["Instagram",config["social.instagram"]],["YouTube",config["social.youtube"]],["LinkedIn",config["social.linkedin"]]].filter((x):x is [string,string]=>Boolean(x[1]));
 return <footer className="site-footer"><div className="container footer-grid"><div><Link href="/" className="logo footer-logo"><img src="/mwonet-logo.svg" alt="MWONET logo"/><span><strong>MWONET</strong><small>Maanisha Western Organization Network</small></span></Link><p>Environmental conservation, enterprise, youth and women empowerment, food security and financial self-reliance rooted in Bungoma County and the Mount Elgon landscape.</p><div className="social-placeholder">{socials.length?socials.map(([label,url])=><a key={label} href={url} target="_blank" rel="noreferrer">{label}</a>):<span>Official social links can be added in Admin → Site Settings.</span>}</div></div><div><h4>Organization</h4>{footerLinks.length?footerLinks.map(x=><Link key={x.href} href={x.href}>{x.label}</Link>):<><Link href="/about">About</Link><Link href="/constitution">Constitution</Link><Link href="/governance">Governance</Link><Link href="/leadership">Leadership</Link><Link href="/membership">Membership</Link></>}</div><div><h4>Our work</h4><Link href="/focus-areas">Programs</Link><Link href="/mount-elgon">Mount Elgon</Link><Link href="/financial-model">Financial model</Link><Link href="/media">Media</Link><Link href="/events">Events</Link></div><div><h4>Official contact</h4><p>{config["organization.address"]}</p><a href={"mailto:"+config["organization.email"]}>{config["organization.email"]}</a>{config["organization.secondaryEmail"]&&<a href={"mailto:"+config["organization.secondaryEmail"]}>{config["organization.secondaryEmail"]}</a>}{config["organization.phone"]&&<a href={"tel:"+config["organization.phone"]}>{config["organization.phone"]}</a>}<Link href="/sign-in">Member sign in</Link><Link href="/register">Join the network</Link></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} MWONET. All rights reserved.</span><span><Link href="/privacy">Privacy</Link> · <Link href="/terms">Terms</Link></span></div></footer>
}
