import {db} from "../../_lib/db";
import {approveFinanceTransaction,createFinanceTransaction,rejectFinanceTransaction} from "./actions";

export const dynamic="force-dynamic";

export default async function FinancePage(){
 const [rows,members]=await Promise.all([
  db.financeTransaction.findMany({orderBy:{occurredAt:"desc"},take:200,include:{member:{include:{user:true}},approver:true}}),
  db.memberProfile.findMany({where:{status:"ACTIVE"},include:{user:true},orderBy:{user:{name:"asc"}}})
 ]);
 const approved=rows.filter(r=>r.status==="APPROVED");
 const total=approved.reduce((s,r)=>s+Number(r.amount),0);
 const pending=rows.filter(r=>r.status==="PENDING").length;
 const byType=(type:string)=>approved.filter(r=>r.type===type).reduce((s,r)=>s+Number(r.amount),0);
 return <main className="admin-content"><div className="admin-page-head"><div><span className="admin-breadcrumb">MWONET Admin / Operations</span><h1>Finance & Revolving Fund</h1><p>Record contributions and approved financial activity with clear references, member links, approval controls and an audit trail. This is a record-management module, not a bank account or payment gateway.</p></div><span className="admin-badge">{rows.length} records</span></div>
 <section className="admin-stat-grid"><article className="admin-stat"><small>APPROVED VALUE</small><strong>KSh {total.toLocaleString("en-KE")}</strong><span>Across approved records</span></article><article className="admin-stat"><small>PENDING</small><strong>{pending}</strong><span>Awaiting review</span></article><article className="admin-stat"><small>REGISTRATION</small><strong>KSh {byType("REGISTRATION_FEE").toLocaleString("en-KE")}</strong><span>Approved registration fees</span></article><article className="admin-stat"><small>MONTHLY</small><strong>KSh {byType("MONTHLY_SUBSCRIPTION").toLocaleString("en-KE")}</strong><span>Approved subscriptions</span></article></section>
 <div className="admin-grid"><section className="admin-panel"><div className="admin-panel-head"><h2>Financial register</h2></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Date</th><th>Member / source</th><th>Type</th><th>Amount</th><th>Reference</th><th>Status</th><th>Review</th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.id}><td>{r.occurredAt.toLocaleDateString("en-KE")}</td><td><strong>{r.member?.user.name||"Organization / external"}</strong><small>{r.member?.memberNumber||r.member?.user.email||r.note||"—"}</small></td><td>{r.type.replaceAll("_"," ")}</td><td><strong>KSh {Number(r.amount).toLocaleString("en-KE")}</strong></td><td>{r.reference||"—"}</td><td><span className="admin-badge">{r.status}</span>{r.approver&&<small>by {r.approver.email}</small>}</td><td>{r.status==="PENDING"?<div style={{display:"flex",gap:6}}><form action={approveFinanceTransaction}><input type="hidden" name="id" value={r.id}/><button className="admin-secondary">Approve</button></form><form action={rejectFinanceTransaction}><input type="hidden" name="id" value={r.id}/><button className="admin-danger">Reject</button></form></div>:"Reviewed"}</td></tr>):<tr><td colSpan={7}>No financial records yet.</td></tr>}</tbody></table></div></section>
 <aside className="admin-side-stack"><section className="admin-editor-section"><h3>Add financial record</h3><form action={createFinanceTransaction} className="admin-form"><label>Member / account<select name="memberId"><option value="">Organization / non-member</option>{members.map(m=><option key={m.id} value={m.id}>{m.user.name||m.user.email} - {m.memberNumber||"member"}</option>)}</select></label><label>Transaction type<select name="type" required><option value="REGISTRATION_FEE">Registration fee</option><option value="MONTHLY_SUBSCRIPTION">Monthly subscription</option><option value="SAVINGS">Savings</option><option value="LOAN_DISBURSEMENT">Loan disbursement</option><option value="LOAN_REPAYMENT">Loan repayment</option><option value="DONATION">Donation</option><option value="PROJECT_INCOME">Project income</option><option value="EXPENSE">Expense</option><option value="OTHER">Other</option></select></label><label>Amount (KSh)<input name="amount" type="number" min="0.01" step="0.01" required/></label><label>Date<input name="occurredAt" type="date"/></label><label>Reference / receipt number<input name="reference" placeholder="Receipt, bank, M-Pesa or voucher reference"/></label><label>Note<textarea name="note" rows={3} placeholder="Purpose, source or supporting explanation."/></label><button className="admin-primary">Save as pending</button></form></section>
 <section className="admin-editor-section"><h3>Financial control rules</h3><div className="admin-config-list"><span className="admin-section-note">New records are created as PENDING and should be reviewed before they count in approved totals.</span><span className="admin-section-note">Treasurer may manage financial records; approval rights can be separated through Roles & Permissions.</span><span className="admin-section-note">Do not use this module as proof of payment without supporting receipts or source documents.</span><span className="admin-section-note">Rejected records remain visible for traceability instead of being silently deleted.</span></div></section></aside></div></main>
}