import Link from "next/link";
import {db} from "../../_lib/db";

export const dynamic="force-dynamic";

export default async function ReportsPage(){
 const [users,members,projects,events,posts,forms,finance,programs]=await Promise.all([
  db.user.count(),db.memberProfile.findMany({include:{user:true}}),db.project.findMany(),db.event.findMany(),db.post.findMany(),db.form.findMany({include:{_count:{select:{submissions:true}}}}),db.financeTransaction.findMany(),db.program.count()
 ]);
 const activeMembers=members.filter(m=>m.status==="ACTIVE").length,pendingMembers=members.filter(m=>m.status==="PENDING").length;
 const approved=finance.filter(f=>f.status==="APPROVED"),approvedValue=approved.reduce((s,f)=>s+Number(f.amount),0);
 const submissions=forms.reduce((s,f)=>s+f._count.submissions,0);
 return <main className="admin-content"><div className="admin-page-head"><div><span className="admin-breadcrumb">MWONET Admin / Operations</span><h1>Reports & Impact</h1><p>A management summary of people, programs, projects, content, participation and approved financial records. Use this area for meetings, accountability and decision-making.</p></div><Link className="admin-primary" href="/admin/reports/export">Download CSV summary</Link></div>
 <section className="admin-stat-grid"><article className="admin-stat"><small>MEMBERS</small><strong>{activeMembers}</strong><span>{pendingMembers} pending · {users} total users</span></article><article className="admin-stat"><small>PROGRAM DELIVERY</small><strong>{projects.length}</strong><span>{programs} programs · {events.length} events</span></article><article className="admin-stat"><small>CONTENT</small><strong>{posts.filter(p=>p.status==="PUBLISHED").length}</strong><span>{posts.length} news records · {submissions} form submissions</span></article><article className="admin-stat"><small>APPROVED FINANCE</small><strong>KSh {approvedValue.toLocaleString("en-KE")}</strong><span>{approved.length} approved records</span></article></section>
 <section className="admin-panel"><div className="admin-panel-head"><h2>Membership report</h2></div><div className="admin-info-grid"><article><strong>Active members</strong><p>{activeMembers} currently approved.</p></article><article><strong>Pending applications</strong><p>{pendingMembers} awaiting membership review.</p></article><article><strong>Suspended / inactive</strong><p>{members.filter(m=>["SUSPENDED","INACTIVE","TERMINATED"].includes(m.status)).length} records outside active membership.</p></article><article><strong>Member numbering</strong><p>{members.filter(m=>m.memberNumber).length} profiles have an issued member number.</p></article></div></section>
 <section className="admin-panel"><div className="admin-panel-head"><h2>Programs & projects</h2></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Status</th><th>Projects</th></tr></thead><tbody>{["PLANNING","ACTIVE","PAUSED","COMPLETED","ARCHIVED"].map(s=><tr key={s}><td>{s}</td><td>{projects.filter(p=>p.status===s).length}</td></tr>)}</tbody></table></div></section>
 <section className="admin-panel"><div className="admin-panel-head"><h2>Publishing & engagement</h2></div><div className="admin-info-grid"><article><strong>Published news</strong><p>{posts.filter(p=>p.status==="PUBLISHED").length} stories are public.</p></article><article><strong>Draft / review news</strong><p>{posts.filter(p=>p.status!=="PUBLISHED").length} stories are still in editorial workflow.</p></article><article><strong>Events</strong><p>{events.filter(e=>e.startsAt>=new Date()).length} upcoming events and {events.filter(e=>e.startsAt<new Date()).length} past events.</p></article><article><strong>Forms</strong><p>{forms.length} forms with {submissions} total submissions.</p></article></div></section>
 <section className="admin-panel"><div className="admin-panel-head"><h2>How to use reports</h2></div><div className="admin-config-list"><span className="admin-section-note">Use reports during leadership meetings to understand membership and project progress.</span><span className="admin-section-note">Use the CSV export for further analysis in Excel or Google Sheets.</span><span className="admin-section-note">Finance totals include APPROVED records only; pending or rejected entries are excluded.</span><span className="admin-section-note">Website traffic analytics require a separate analytics provider; this report focuses on data already owned by MWONET.</span></div></section></main>
}