import Link from "next/link";
import {images,programs} from "./data/site";

export default function Home(){return <>
<section className="home-hero" style={{backgroundImage:`linear-gradient(90deg,rgba(7,34,24,.90) 0%,rgba(7,34,24,.58) 52%,rgba(7,34,24,.22) 100%),url(${images.mountain})`}}><div className="container home-hero-grid"><div><p className="eyebrow light">MAANISHA WESTERN ORGANIZATION NETWORK</p><h1>People. Nature.<br/><span>Lasting Impact.</span></h1><p>Working with communities to protect nature, empower young people and build sustainable solutions around Mount Elgon and beyond.</p><div className="hero-actions"><Link className="button primary" href="/focus-areas">Explore our work</Link><Link className="button outline-light" href="/get-involved">Get involved</Link></div></div><div className="impact-panel"><small>OUR LANDSCAPE</small><strong>Mount Elgon</strong><p>Forests • Farms • Water • Communities</p><Link href="/mount-elgon">Discover the landscape →</Link></div></div></section>
<section className="section"><div className="container intro-grid"><div><p className="eyebrow">WHO WE ARE</p><h2>Community action rooted in people and place.</h2></div><div><p className="big-copy">MWONET brings together environmental stewardship, youth participation and community development in a platform designed for long-term impact.</p><p className="notice">Official history, mission, vision and constitutional objectives will be refined from the organization’s approved documents.</p><Link className="text-link" href="/about">Read our story →</Link></div></div></section>
<section className="section tint"><div className="container"><div className="section-head"><div><p className="eyebrow">FOCUS AREAS</p><h2>Practical pathways to change.</h2></div><Link className="text-link" href="/focus-areas">View all programs →</Link></div><div className="card-grid three">{programs.map((p,i)=><article className="program-card" key={p.slug}><span className="icon">{p.icon}</span><small>0{i+1}</small><h3>{p.title}</h3><p>{p.summary}</p><Link href={`/focus-areas/${p.slug}`}>Explore program →</Link></article>)}</div></div></section>
<section className="feature-split"><div className="feature-image" style={{backgroundImage:`url(${images.forest})`}}/><div className="feature-copy"><p className="eyebrow light">MOUNT ELGON & OUR ENVIRONMENT</p><h2>A living landscape worth protecting.</h2><p>Discover forests, biodiversity, water sources, soil erosion, farming on slopes and the conservation actions shaping the future of the mountain.</p><Link className="button light-button" href="/mount-elgon">Explore Mount Elgon</Link></div></section>
<section className="section"><div className="container"><div className="section-head"><div><p className="eyebrow">RESTORATION IN ACTION</p><h2>From nursery beds to healthier landscapes.</h2></div><Link className="text-link" href="/tree-restoration">Explore restoration →</Link></div><div className="photo-grid"><article className="photo-card wide" style={{backgroundImage:`url(${images.seedlings})`}}><span>Tree nurseries</span><strong>Growing the next forest</strong></article><article className="photo-card" style={{backgroundImage:`url(${images.community})`}}><span>Youth & community</span><strong>People taking action</strong></article><article className="photo-card" style={{backgroundImage:`url(${images.farming})`}}><span>Sustainable agriculture</span><strong>Protecting soil and livelihoods</strong></article></div></div></section>
<section className="section dark"><div className="container cta-grid"><div><p className="eyebrow light">JOIN THE NETWORK</p><h2>Help shape a greener and more resilient future.</h2><p>Volunteer, partner, support a project or create an account to stay connected with MWONET activities.</p></div><div className="cta-actions"><Link className="button light-button" href="/register">Create account</Link><Link className="button outline-light" href="/get-involved">Ways to get involved</Link></div></div></section>
</>}
