import {getAdminSession} from "../../_lib/auth";
import {requirePermission} from "../../_lib/access";

export const dynamic="force-dynamic";
export default async function EmailPage(){
 const session=await getAdminSession();if(!session)throw new Error("Not signed in");await requirePermission(session.email,"manage_email");
 return <main className="admin-content"><div className="admin-page-head"><div><span className="admin-breadcrumb">MWONET Admin / Operations</span><h1>Email & Communications</h1><p>Understand exactly what the official-domain email can do today and which optional service is needed for authenticated outgoing mail.</p></div><span className="admin-badge">Inbound live</span></div>
 <section className="admin-stat-grid"><article className="admin-stat"><small>DOMAIN</small><strong>mwonet.org</strong><span>Official organization domain</span></article><article className="admin-stat"><small>INCOMING</small><strong>Working</strong><span>Cloudflare Email Routing</span></article><article className="admin-stat"><small>PUBLIC ADDRESS</small><strong>info@</strong><span>Receives and forwards mail</span></article><article className="admin-stat"><small>OUTGOING</small><strong>Optional package</strong><span>Mailbox / SMTP required</span></article></section>
 <section className="admin-panel"><div className="admin-panel-head"><h2>How the current email works</h2></div><div className="admin-info-grid"><article><strong>Receiving</strong><p>A sender can email <b>info@mwonet.org</b>. Cloudflare receives the message and forwards it to the verified destination Gmail or mailbox configured in Email Routing.</p></article><article><strong>Sending</strong><p>Cloudflare Email Routing is not a full outgoing mailbox. To send authenticated mail that visibly comes from <b>info@mwonet.org</b>, MWONET must approve a professional mailbox or SMTP service.</p></article><article><strong>Portal notices</strong><p>Announcements inside the member portal are already built into MWONET and do not require an email package.</p></article><article><strong>Security</strong><p>Do not store email passwords, SMTP passwords or provider API keys inside Site Settings or public pages.</p></article></div></section>
 <section className="admin-panel"><div className="admin-panel-head"><h2>Handover checklist</h2></div><div className="admin-config-list"><span className="admin-section-note">Confirm the client Gmail or mailbox that should receive info@mwonet.org messages.</span><span className="admin-section-note">In Cloudflare Email Routing, verify that destination address and point the info rule to it.</span><span className="admin-section-note">Send a test message from a different email account and confirm delivery.</span><span className="admin-section-note">Only purchase an outbound mailbox/SMTP package if MWONET needs to send as info@mwonet.org.</span><span className="admin-section-note">After an outbound provider is purchased, add its DNS records in Cloudflare exactly as the provider instructs; do not remove the Vercel website records.</span></div></section>
 <section className="admin-panel"><div className="admin-panel-head"><h2>What is complete vs external</h2></div><p className="admin-section-note"><strong>Complete in the platform:</strong> official domain, website, DNS routing, incoming email, contact forms, portal announcements and communication records. <strong>External choice:</strong> authenticated outgoing domain email. That is a service subscription decision, not unfinished website development.</p></section>
 </main>
}
