import {notFound} from "next/navigation";
import Link from "next/link";
import {db} from "../../../_lib/db";
import {deleteResource,updateEvent,updateFormDefinition,updateLeader,updateNavigation,updatePartner,updatePost,updateProgram,updateProject} from "../../../resource-actions";

export const dynamic="force-dynamic";
const dt=(d:Date|null|undefined)=>d?new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16):"";
const date=(d:Date|null|undefined)=>d?d.toISOString().slice(0,10):"";
const body=(v:unknown)=>v&&typeof v==="object"&&!Array.isArray(v)?String((v as Record<string,unknown>).body||""):"";
const fields=(v:unknown)=>v&&typeof v==="object"&&!Array.isArray(v)&&Array.isArray((v as Record<string,unknown>).fields)?((v as Record<string,unknown>).fields as unknown[]).map(String).join(", "):"";

export default async function ResourceEditor({params}:{params:Promise<{type:string;id:string}>}){
 const {type,id}=await params;
 let title="",back="/admin",form:React.ReactNode=null,canDelete=false;
 if(type==="program"){const x=await db.program.findUnique({where:{id}});if(!x)return notFound();title="Edit program";back="/admin/programs";form=<form action={updateProgram} className="admin-form admin-form-grid"><input type="hidden" name="id" value={id}/><label>Program title<input name="title" defaultValue={x.title} required/></label><label>Slug<input name="slug" defaultValue={x.slug}/></label><label className="admin-span-2">Summary<textarea name="summary" rows={3} defaultValue={x.summary||""}/></label><label className="admin-span-2">Detailed content<textarea name="content" rows={8} defaultValue={body(x.content)}/></label><button className="admin-primary">Save program</button></form>}
 else if(type==="project"){const [x,programs]=await Promise.all([db.project.findUnique({where:{id}}),db.program.findMany({orderBy:{title:"asc"}})]);if(!x)return notFound();title="Edit project";back="/admin/projects";form=<form action={updateProject} className="admin-form admin-form-grid"><input type="hidden" name="id" value={id}/><label>Project title<input name="title" defaultValue={x.title} required/></label><label>Slug<input name="slug" defaultValue={x.slug}/></label><label>Program<select name="programId" defaultValue={x.programId||""}><option value="">Unassigned</option>{programs.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><label>Status<select name="status" defaultValue={x.status}><option>PLANNING</option><option>ACTIVE</option><option>PAUSED</option><option>COMPLETED</option><option>ARCHIVED</option></select></label><label>Location<input name="location" defaultValue={x.location||""}/></label><label>Start date<input type="date" name="startDate" defaultValue={date(x.startDate)}/></label><label>End date<input type="date" name="endDate" defaultValue={date(x.endDate)}/></label><label className="admin-span-2">Summary<textarea name="summary" rows={3} defaultValue={x.summary||""}/></label><label className="admin-span-2">Detailed content<textarea name="content" rows={8} defaultValue={body(x.content)}/></label><button className="admin-primary">Save project</button></form>}
 else if(type==="post"){const x=await db.post.findUnique({where:{id}});if(!x)return notFound();title="Edit news story";back="/admin/posts";canDelete=true;form=<form action={updatePost} className="admin-form admin-form-grid"><input type="hidden" name="id" value={id}/><label>Headline<input name="title" defaultValue={x.title} required/></label><label>Slug<input name="slug" defaultValue={x.slug}/></label><label>Status<select name="status" defaultValue={x.status}><option>DRAFT</option><option>REVIEW</option><option>PUBLISHED</option><option>ARCHIVED</option></select></label><label className="admin-span-2">Excerpt<textarea name="excerpt" rows={3} defaultValue={x.excerpt||""}/></label><label className="admin-span-2">Story<textarea name="content" rows={12} defaultValue={body(x.content)}/></label><button className="admin-primary">Save story</button></form>}
 else if(type==="event"){const x=await db.event.findUnique({where:{id}});if(!x)return notFound();title="Edit event";back="/admin/events";canDelete=true;form=<form action={updateEvent} className="admin-form admin-form-grid"><input type="hidden" name="id" value={id}/><label>Event title<input name="title" defaultValue={x.title} required/></label><label>Slug<input name="slug" defaultValue={x.slug}/></label><label>Venue<input name="venue" defaultValue={x.venue||""}/></label><label>Status<select name="status" defaultValue={x.status}><option>DRAFT</option><option>REVIEW</option><option>PUBLISHED</option><option>ARCHIVED</option></select></label><label>Starts<input type="datetime-local" name="startsAt" defaultValue={dt(x.startsAt)} required/></label><label>Ends<input type="datetime-local" name="endsAt" defaultValue={dt(x.endsAt)}/></label><label className="admin-span-2">Description<textarea name="description" rows={6} defaultValue={x.description||""}/></label><button className="admin-primary">Save event</button></form>}
 else if(type==="leader"){const x=await db.leadershipProfile.findUnique({where:{id}});if(!x)return notFound();title="Edit leadership profile";back="/admin/leadership";canDelete=true;form=<form action={updateLeader} className="admin-form admin-form-grid"><input type="hidden" name="id" value={id}/><label>Full name<input name="name" defaultValue={x.name} required/></label><label>Official role<input name="role" defaultValue={x.role} required/></label><label>Photo URL<input name="photoUrl" defaultValue={x.photoUrl||""}/></label><label>Email<input type="email" name="email" defaultValue={x.email||""}/></label><label>Phone<input name="phone" defaultValue={x.phone||""}/></label><label>Display order<input type="number" name="order" defaultValue={x.order}/></label><label>Status<select name="active" defaultValue={x.active?"true":"false"}><option value="true">Active</option><option value="false">Inactive</option></select></label><label className="admin-span-2">Biography<textarea name="bio" rows={7} defaultValue={x.bio||""}/></label><button className="admin-primary">Save leader</button></form>}
 else if(type==="partner"){const x=await db.partner.findUnique({where:{id}});if(!x)return notFound();title="Edit partner";back="/admin/partners";canDelete=true;form=<form action={updatePartner} className="admin-form admin-form-grid"><input type="hidden" name="id" value={id}/><label>Organization name<input name="name" defaultValue={x.name} required/></label><label>Category<input name="category" defaultValue={x.category||""}/></label><label>Website<input name="website" defaultValue={x.website||""}/></label><label>Logo URL<input name="logoUrl" defaultValue={x.logoUrl||""}/></label><label>Status<select name="active" defaultValue={x.active?"true":"false"}><option value="true">Active</option><option value="false">Inactive</option></select></label><label className="admin-span-2">Description<textarea name="description" rows={6} defaultValue={x.description||""}/></label><button className="admin-primary">Save partner</button></form>}
 else if(type==="navigation"){const x=await db.navigationItem.findUnique({where:{id}});if(!x)return notFound();title="Edit navigation item";back="/admin/navigation";form=<form action={updateNavigation} className="admin-form admin-form-grid"><input type="hidden" name="id" value={id}/><label>Label<input name="label" defaultValue={x.label} required/></label><label>Link / path<input name="href" defaultValue={x.href} required/></label><label>Location<select name="location" defaultValue={x.location}><option value="header">Header</option><option value="footer">Footer</option><option value="portal">Portal</option></select></label><label>Order<input type="number" name="order" defaultValue={x.order}/></label><label>Visible<select name="visible" defaultValue={x.visible?"true":"false"}><option value="true">Yes</option><option value="false">No</option></select></label><button className="admin-primary">Save navigation</button></form>}
 else if(type==="form"){const x=await db.form.findUnique({where:{id}});if(!x)return notFound();title="Edit form";back="/admin/forms";form=<form action={updateFormDefinition} className="admin-form admin-form-grid"><input type="hidden" name="id" value={id}/><label>Form name<input name="name" defaultValue={x.name} required/></label><label>Key<input name="key" defaultValue={x.key} required/></label><label className="admin-span-2">Fields - comma separated<textarea name="fields" rows={5} defaultValue={fields(x.schema)}/></label><button className="admin-primary">Save form</button></form>}
 else return notFound();
 return <main className="admin-content"><div className="admin-page-head"><div><span className="admin-breadcrumb">MWONET Admin / Edit</span><h1>{title}</h1><p>Changes are saved to the MWONET database and recorded in the audit trail.</p></div><Link className="admin-secondary" href={back}>← Back</Link></div><section className="admin-panel">{form}</section>{canDelete&&<section className="admin-panel"><div className="admin-panel-head"><h2>Permanent deletion</h2><span className="admin-badge">Super Admin only</span></div><p className="admin-section-note">Administrators should normally archive or deactivate records. Permanent deletion is restricted to Super Admin.</p><form action={deleteResource}><input type="hidden" name="type" value={type}/><input type="hidden" name="id" value={id}/><button className="admin-danger">Permanently delete</button></form></section>}</main>
}
