import Link from "next/link";
import {db} from "../admin/_lib/db";
import {accountRef,requireMember} from "../_lib/member-auth";
import {changeMemberPasswordAction,memberLogoutAction,updateMemberProfileAction} from "./actions";

export const dynamic="force-dynamic";
export const metadata={title:"Member Portal",description:"Secure MWONET member portal for membership status, opportunities and account management."};

export default async function Portal({searchParams}:{searchParams:Promise<{welcome?:string;profileSaved?:string;passwordChanged?:string;error?:string}>}){
 const user=await requireMember();const {welcome,profileSaved,passwordChanged,error}=await searchParams;const member=user.member;
 const [programs,events,posts]=await Promise.all([
  db.program.findMany({orderBy:{title:"asc"},take:6}),
  db.event.findMany({where:{startsAt:{gte:new Date()},status:"PUBLISHED"},orderBy:{startsAt:"asc"},take:4}),
  db.post.findMany({where:{status:"PUBLISHED"},orderBy:{publishedAt:"desc"},take:4})
 ]);
 const status=member?.status||"PENDING";const isActive=status==="ACTIVE";
 return <section className="member-portal"><div className="member-portal-top"><div className="container member-portal-top-inner"><div><p className="eyebrow light">MWONET MEMBER PORTAL</p><h1>Welcome, {user.name||"Member"}</h1><p>Account ref: <strong>{accountRef(user.email)}</strong> · {user.email}</p></div><form action={memberLogoutAction}><button className="button outline-light" type="submit">Sign out</button></form></div></div><div className="container member-portal-body">{welcome&&<div className="portal-alert success">Your secure account has been created. Your membership application is now awaiting MWONET review.</div>}{profileSaved&&<div className="portal-alert success">Profile details updated successfully.</div>}{passwordChanged&&<div className="portal-alert success">Your password has been changed successfully.</div>}{error&&<div className="portal-alert error">{error}</div>}
 <section className="portal-summary-grid"><article><small>MEMBERSHIP STATUS</small><strong className={isActive?"portal-status-active":"portal-status-pending"}>{status}</strong><span>{isActive?"Approved membership":"Awaiting administrative review"}</span></article><article><small>MEMBER NUMBER</small><strong>{member?.memberNumber||"Pending"}</strong><span>Assigned after approval where applicable</span></article><article><small>REGISTRATION FEE</small><strong>KSh {member?.registrationFee?.toString()||"1,000"}</strong><span>Payment confirmation is handled by MWONET</span></article><article><small>MONTHLY SUBSCRIPTION</small><strong>KSh {member?.monthlyFee?.toString()||"200"}</strong><span>Constitutional monthly subscription</span></article></section>
 <div className="portal-main-grid"><div className="portal-main-column"><section className="portal-panel"><div className="portal-panel-head"><div><p className="eyebrow">MEMBERSHIP</p><h2>Your profile</h2></div><span className="portal-chip">{status}</span></div><div className="portal-profile-grid"><div><small>Full name</small><strong>{user.name||"—"}</strong></div><div><small>Email</small><strong>{user.email}</strong></div><div><small>Phone</small><strong>{member?.phone||"—"}</strong></div><div><small>Area</small><strong>{member?.county||"—"}</strong></div><div><small>Date of birth</small><strong>{member?.dateOfBirth?.toLocaleDateString("en-KE")||"—"}</strong></div><div><small>Last sign-in</small><strong>{user.lastLoginAt?.toLocaleString("en-KE")||"Current session"}</strong></div></div><details className="portal-details"><summary>Edit contact profile</summary><form action={updateMemberProfileAction} className="portal-form"><label>Phone<input name="phone" defaultValue={member?.phone||""} required/></label><label>Membership area<select name="county" defaultValue={member?.county||"Bungoma County"}><option>Bungoma County</option></select></label><button className="button primary" type="submit">Save profile</button></form></details></section>
 <section className="portal-panel"><div className="portal-panel-head"><div><p className="eyebrow">PROGRAMS</p><h2>Where MWONET is working</h2></div><Link href="/focus-areas">Explore all →</Link></div><div className="portal-card-grid">{programs.map(p=><article key={p.id}><span>PROGRAM</span><h3>{p.title}</h3><p>{p.summary||"Structured MWONET program."}</p></article>)}</div></section>
 <section className="portal-panel"><div className="portal-panel-head"><div><p className="eyebrow">OPPORTUNITIES</p><h2>Upcoming events</h2></div><Link href="/events">View events →</Link></div>{events.length?<div className="portal-list">{events.map(e=><article key={e.id}><div><small>{e.startsAt.toLocaleDateString("en-KE")}</small><h3>{e.title}</h3><p>{e.venue||"Venue to be communicated"}</p></div><span>{e.status}</span></article>)}</div>:<div className="portal-empty">No published upcoming events yet. New events will appear here automatically.</div>}</section></div>
 <aside className="portal-side-column"><section className="portal-panel"><p className="eyebrow">APPLICATION PROGRESS</p><h2>Membership journey</h2><div className="portal-steps"><div className="done"><i>1</i><span><b>Account created</b><small>Secure credentials stored.</small></span></div><div className="done"><i>2</i><span><b>Profile submitted</b><small>Eligibility information received.</small></span></div><div className={isActive?"done":"current"}><i>3</i><span><b>Administrative review</b><small>{isActive?"Approved":"Pending review"}</small></span></div><div className={isActive?"done":""}><i>4</i><span><b>Active membership</b><small>Access according to MWONET policy.</small></span></div></div></section>
 <section className="portal-panel"><p className="eyebrow">ACCOUNT SECURITY</p><h2>Change password</h2><details className="portal-details"><summary>Open password settings</summary><form action={changeMemberPasswordAction} className="portal-form"><label>Current password<input name="currentPassword" type="password" autoComplete="current-password" required/></label><label>New password<input name="newPassword" type="password" autoComplete="new-password" minLength={10} required/></label><label>Confirm new password<input name="confirmPassword" type="password" autoComplete="new-password" minLength={10} required/></label><button className="button primary" type="submit">Update password</button></form></details><p className="portal-note">Use at least 10 characters with uppercase, lowercase and a number.</p></section>
 <section className="portal-panel"><p className="eyebrow">LATEST UPDATES</p><h2>News</h2>{posts.length?<div className="portal-news-mini">{posts.map(p=><article key={p.id}><small>{p.publishedAt?.toLocaleDateString("en-KE")||"Update"}</small><strong>{p.title}</strong></article>)}</div>:<div className="portal-empty">No published news yet.</div>}<Link className="text-link" href="/news">Visit News →</Link></section>
 <section className="portal-panel"><p className="eyebrow">IMPORTANT</p><h2>Membership records</h2><p className="portal-note">This portal does not mark fees as paid unless MWONET records and confirms them. Loan, savings and revolving-fund functions will only appear when the finance module and policies are formally activated.</p><Link className="text-link" href="/constitution">Read Constitution →</Link></section></aside></div></div></section>
}
