import {getAdminSession} from "../../_lib/auth";
import {requirePermission} from "../../_lib/access";
import {db} from "../../_lib/db";
import {createNotification,updateNotificationStatus} from "./actions";

export const dynamic="force-dynamic";

export default async function NotificationsPage(){const session=await getAdminSession();if(!session)throw new Error("Not signed in");await requirePermission(session.email,"manage_notifications");
 const rows=await db.notification.findMany({orderBy:{createdAt:"desc"},take:200,include:{creator:true}});
 const published=rows.filter(r=>r.status==="PUBLISHED").length,drafts=rows.filter(r=>r.status==="DRAFT").length;
 return <main className="admin-content"><div className="admin-page-head"><div><span className="admin-breadcrumb">MWONET Admin / Operations</span><h1>Notifications</h1><p>Create announcements that appear inside the member portal. Email, SMS or push delivery can be added later only if MWONET approves an external provider.</p></div><span className="admin-badge">{rows.length} notices</span></div>
 <section className="admin-stat-grid"><article className="admin-stat"><small>PUBLISHED</small><strong>{published}</strong><span>Visible in member portal</span></article><article className="admin-stat"><small>DRAFTS</small><strong>{drafts}</strong><span>Not visible to members</span></article><article className="admin-stat"><small>CHANNEL</small><strong>Portal</strong><span>Built-in zero-cost delivery</span></article><article className="admin-stat"><small>EXTERNAL CHANNELS</small><strong>Optional</strong><span>Email / SMS require provider</span></article></section>
 <div className="admin-grid"><section className="admin-panel"><div className="admin-panel-head"><h2>Announcement history</h2></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Announcement</th><th>Audience</th><th>Status</th><th>Date</th><th>Action</th></tr></thead><tbody>{rows.length?rows.map(n=><tr key={n.id}><td><strong>{n.title}</strong><small>{n.message}</small></td><td>{n.audience.replaceAll("_"," ")}</td><td><span className="admin-badge">{n.status}</span></td><td>{(n.publishedAt||n.createdAt).toLocaleString("en-KE")}</td><td><form action={updateNotificationStatus} className="admin-inline-form"><input type="hidden" name="id" value={n.id}/><select name="status" defaultValue={n.status}><option>DRAFT</option><option>PUBLISHED</option><option>ARCHIVED</option></select><button className="admin-secondary">Save</button></form></td></tr>):<tr><td colSpan={5}>No announcements yet.</td></tr>}</tbody></table></div></section>
 <aside className="admin-side-stack"><section className="admin-editor-section"><h3>Create announcement</h3><form action={createNotification} className="admin-form"><label>Title<input name="title" required placeholder="e.g. Annual General Meeting notice"/></label><label>Message<textarea name="message" rows={6} required placeholder="Write a clear notice members can understand."/></label><label>Audience<select name="audience"><option value="ALL_MEMBERS">All members</option><option value="ACTIVE_MEMBERS">Active members</option><option value="LEADERSHIP">Leadership</option></select></label><label>Status<select name="status"><option>DRAFT</option><option>PUBLISHED</option></select></label><button className="admin-primary">Save announcement</button></form></section>
 <section className="admin-editor-section"><h3>Communication rule</h3><p className="admin-section-note">Portal announcements are fully built into MWONET and do not require another service. Sending from info@mwonet.org, bulk email, SMS or push notifications depends on an approved external sending provider and is therefore treated as an optional integration, not an unfinished website feature.</p></section></aside></div></main>
}