import {notFound} from "next/navigation";import Link from "next/link";import PageHero from "../../components/PageHero";import {images,programs} from "../../data/site";
const detail:{[key:string]:{objective:string;activities:string[];outcomes:string[];image:string}}={
 "environmental-conservation":{objective:"Build practical community systems for afforestation and environmental sustainability through tree seedling nurseries and restoration.",activities:["Establish and manage community tree nurseries","Raise indigenous and suitable tree seedlings","Coordinate planting and restoration activities","Promote environmental awareness and stewardship"],outcomes:["More locally available seedlings","Restored and greener community spaces","Stronger participation in conservation","Visible environmental responsibility"],image:images.seedlings},
 "agribusiness-livestock":{objective:"Develop commercial and sustainable livestock enterprises that can strengthen member income and household resilience.",activities:["Modern chicken rearing","Goat farming","Livestock multiplication","Enterprise skills and practical farm management"],outcomes:["Stronger member enterprises","Diversified household income","Improved livestock productivity","Practical youth livelihood opportunities"],image:images.livestock},
 "coffee-cash-crops":{objective:"Use high-yielding coffee seedling nurseries to strengthen local production and improve member income.",activities:["Coffee seedling nursery development","Seedling care and quality management","Farmer outreach and distribution","Cash-crop enterprise development"],outcomes:["Improved seedling access","Higher-quality local production potential","Income opportunities from nurseries","Stronger long-term cash-crop value chains"],image:images.coffee},
 "financial-pooling-microcredit":{objective:"Provide a transparent internal revolving fund that helps fully participating members access affordable enterprise capital.",activities:["Member savings and contributions","Transparent record keeping","Member loan applications and guarantorship","Revolving-fund monitoring and repayment tracking"],outcomes:["Better access to enterprise capital","Stronger savings culture","Transparent member finance","A growing internal fund"],image:images.community},
 "youth-women-empowerment":{objective:"Translate MWONET’s mission into opportunities for youth and women to participate in climate action, enterprise, leadership and local development.",activities:["Skills and enterprise participation","Environmental action","Community outreach","Leadership and project involvement"],outcomes:["Greater participation","Stronger enterprise confidence","Local leadership pathways","Youth and women visible in community solutions"],image:images.community},
 "food-security-resilience":{objective:"Connect sustainable farming, enterprise and environmental protection to stronger household food security and community resilience.",activities:["Sustainable farming promotion","Soil and water stewardship","Livelihood diversification","Community learning and demonstration"],outcomes:["Improved resilience","More sustainable production","Protected natural resources","Stronger household livelihood options"],image:images.farming}
};
export function generateStaticParams(){return programs.map(p=>({slug:p.slug}))}
export default async function ProgramPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=programs.find(x=>x.slug===slug);const d=detail[slug];if(!p||!d)return notFound();return <><PageHero eyebrow="MWONET program" title={p.title} text={p.summary} image={d.image}/><section className="section"><div className="container intro-grid"><div><p className="eyebrow">CONSTITUTIONAL PURPOSE</p><h2>From objective to field action.</h2></div><div><p className="big-copy">{d.objective}</p><p className="notice">Project targets, dates, budgets, beneficiaries and verified impact figures will be added from MWONET’s approved project records as they become available.</p></div></div></section><section className="section tint"><div className="container program-detail-grid"><article><p className="eyebrow">PRACTICAL ACTIVITIES</p><h2>What this program can do.</h2>{d.activities.map((a,i)=><div className="activity-row" key={a}><span>{String(i+1).padStart(2,"0")}</span><p>{a}</p></div>)}</article><article><p className="eyebrow">INTENDED OUTCOMES</p><h2>What progress should look like.</h2>{d.outcomes.map((a,i)=><div className="activity-row" key={a}><span>{String(i+1).padStart(2,"0")}</span><p>{a}</p></div>)}</article></div></section><section className="section"><div className="container cta-box"><div><p className="eyebrow">PARTNER WITH THIS PROGRAM</p><h2>Turn shared priorities into practical action.</h2></div><Link className="button primary" href="/get-involved/partner">Partner with MWONET</Link></div></section></>}
