import {notFound} from "next/navigation";
import Link from "next/link";
import PageHero from "../../components/PageHero";
import {images,programs as programSeed} from "../../data/site";
import {db} from "../../admin/_lib/db";

const detail:{[key:string]:{objective:string;activities:string[];outcomes:string[];image:string}}={
 "environmental-conservation":{objective:"Build practical community systems for afforestation and environmental sustainability through tree seedling nurseries and restoration.",activities:["Establish and manage community tree nurseries","Raise indigenous and suitable tree seedlings","Coordinate planting and restoration activities","Promote environmental awareness and stewardship"],outcomes:["More locally available seedlings","Restored and greener community spaces","Stronger participation in conservation","Visible environmental responsibility"],image:images.seedlings},
 "agribusiness-livestock":{objective:"Develop commercial and sustainable livestock enterprises that can strengthen member income and household resilience.",activities:["Modern chicken rearing","Goat farming","Livestock multiplication","Enterprise skills and practical farm management"],outcomes:["Stronger member enterprises","Diversified household income","Improved livestock productivity","Practical youth livelihood opportunities"],image:images.livestock},
 "coffee-cash-crops":{objective:"Use high-yielding coffee seedling nurseries to strengthen local production and improve member income.",activities:["Coffee seedling nursery development","Seedling care and quality management","Farmer outreach and distribution","Cash-crop enterprise development"],outcomes:["Improved seedling access","Higher-quality local production potential","Income opportunities from nurseries","Stronger long-term cash-crop value chains"],image:images.coffee},
 "financial-pooling-microcredit":{objective:"Provide a transparent internal revolving fund that helps fully participating members access affordable enterprise capital.",activities:["Member savings and contributions","Transparent record keeping","Member loan applications and guarantorship","Revolving-fund monitoring and repayment tracking"],outcomes:["Better access to enterprise capital","Stronger savings culture","Transparent member finance","A growing internal fund"],image:images.community},
 "youth-women-empowerment":{objective:"Translate MWONET’s mission into opportunities for youth and women to participate in climate action, enterprise, leadership and local development.",activities:["Skills and enterprise participation","Environmental action","Community outreach","Leadership and project involvement"],outcomes:["Greater participation","Stronger enterprise confidence","Local leadership pathways","Youth and women visible in community solutions"],image:images.community},
 "food-security-resilience":{objective:"Connect sustainable farming, enterprise and environmental protection to stronger household food security and community resilience.",activities:["Sustainable farming promotion","Soil and water stewardship","Livelihood diversification","Community learning and demonstration"],outcomes:["Improved resilience","More sustainable production","Protected natural resources","Stronger household livelihood options"],image:images.farming}
};
export const dynamic="force-dynamic";
export function generateStaticParams(){return programSeed.map(p=>({slug:p.slug}))}
export default async function ProgramPage({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;const [record,projects]=await Promise.all([db.program.findUnique({where:{slug}}),db.project.findMany({where:{program:{slug},status:{in:["ACTIVE","COMPLETED"]}},orderBy:{title:"asc"}})]);
 const seed=programSeed.find(x=>x.slug===slug);const d=detail[slug];if(!record&&!seed)return notFound();
 const p=record||seed!;const body=record?.content&&typeof record.content==="object"&&!Array.isArray(record.content)?String((record.content as Record<string,unknown>).body||""):"";const info=d||{objective:p.summary||"MWONET program.",activities:[],outcomes:[],image:images.community};
 return <><PageHero eyebrow="MWONET program" title={p.title} text={p.summary||"Official MWONET program."} image={info.image}/><section className="section"><div className="container intro-grid"><div><p className="eyebrow">PROGRAM PURPOSE</p><h2>From objective to field action.</h2></div><div><p className="big-copy">{info.objective}</p>{body&&body.split(/\n\n+/).filter(Boolean).map((x,i)=><p key={i}>{x}</p>)}</div></div></section>{(info.activities.length>0||info.outcomes.length>0)&&<section className="section tint"><div className="container program-detail-grid"><article><p className="eyebrow">PRACTICAL ACTIVITIES</p><h2>What this program can do.</h2>{info.activities.map((a,i)=><div className="activity-row" key={a}><span>{String(i+1).padStart(2,"0")}</span><p>{a}</p></div>)}</article><article><p className="eyebrow">INTENDED OUTCOMES</p><h2>What progress should look like.</h2>{info.outcomes.map((a,i)=><div className="activity-row" key={a}><span>{String(i+1).padStart(2,"0")}</span><p>{a}</p></div>)}</article></div></section>}{projects.length>0&&<section className="section"><div className="container"><div className="section-head"><div><p className="eyebrow">PROJECTS</p><h2>Projects under this program.</h2></div></div><div className="program-grid">{projects.map(project=><Link className="program-card" href={`/projects/${project.slug}`} key={project.id}><small>{project.status}</small><h3>{project.title}</h3><p>{project.summary||project.location||"MWONET project"}</p><span>View project →</span></Link>)}</div></div></section>}<section className="section"><div className="container cta-box"><div><p className="eyebrow">PARTNER WITH THIS PROGRAM</p><h2>Turn shared priorities into practical action.</h2></div><Link className="button primary" href="/get-involved/partner">Partner with MWONET</Link></div></section></>
}
