import {getAdminSession} from "../../_lib/auth";
import {requirePermission} from "../../_lib/access";
import {db} from "../../_lib/db";
import {ensureSystemCatalog} from "../../_lib/cms";
import {createCustomRoleAction,toggleRolePermissionAction} from "./actions";

export const dynamic="force-dynamic";

export default async function RolesPage(){const session=await getAdminSession();if(!session)throw new Error("Not signed in");await requirePermission(session.email,"manage_roles");
 await ensureSystemCatalog();
 const [roles,permissions]=await Promise.all([
  db.role.findMany({orderBy:{name:"asc"},include:{permissions:{include:{permission:true}},_count:{select:{users:true}}}}),
  db.permission.findMany({orderBy:{key:"asc"}})
 ]);
 return <main className="admin-content"><div className="admin-page-head"><div><span className="admin-breadcrumb">MWONET Admin / Security</span><h1>Roles & Permissions</h1><p>Control exactly what each category of staff or leader can see and do. Super Admin remains the only owner-level role.</p></div><span className="admin-badge">{roles.length} roles</span></div>
 <section className="admin-panel"><div className="admin-panel-head"><h2>Create a custom role</h2><span className="admin-badge">Super Admin only</span></div><form action={createCustomRoleAction} className="admin-form admin-form-grid"><label>Role name<input name="name" placeholder="e.g. Communications Officer" required/></label><label className="admin-span-2">Description<textarea name="description" rows={3} placeholder="Explain the responsibility and intended access."/></label><button className="admin-primary">Create role</button></form></section>
 <section className="admin-panel"><div className="admin-panel-head"><h2>Permission matrix</h2><span className="admin-badge">{permissions.length} permissions</span></div><p className="admin-section-note">A checked permission means that role may access the corresponding function. Super Admin is intentionally locked with full access and cannot be reduced from this screen.</p><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Role</th><th>Users</th><th>Description</th><th>Permissions</th></tr></thead><tbody>{roles.map(role=>{const active=new Set(role.permissions.map(x=>x.permissionId));return <tr key={role.id}><td><strong>{role.name}</strong>{role.name==="Super Admin"&&<small>Protected owner role</small>}</td><td>{role._count.users}</td><td>{role.description||"—"}</td><td><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:6}}>{permissions.map(p=>{const on=role.name==="Super Admin"||active.has(p.id);return <form key={p.id} action={toggleRolePermissionAction}><input type="hidden" name="roleId" value={role.id}/><input type="hidden" name="permissionId" value={p.id}/><input type="hidden" name="enabled" value={on?"0":"1"}/><button className={on?"admin-badge":"admin-secondary"} disabled={role.name==="Super Admin"} title={p.description||p.key}>{on?"✓ ":""}{p.key.replaceAll("_"," ")}</button></form>})}</div></td></tr>})}</tbody></table></div></section>
 <section className="admin-panel"><div className="admin-panel-head"><h2>Recommended MWONET access model</h2></div><div className="admin-info-grid"><article><strong>Super Admin</strong><p>System owner. Full control over roles, plugins, themes, users, settings and all content. Keep this role with the technical owner only.</p></article><article><strong>Administrator</strong><p>Runs normal day-to-day administration and editing, but should not control ownership-level security or destructive system features.</p></article><article><strong>Chairperson / Secretary</strong><p>Leadership and governance access focused on members, programs, reports, events and official communication.</p></article><article><strong>Treasurer</strong><p>Finance and reporting permissions only, with audit visibility and no theme/plugin/system ownership.</p></article><article><strong>Editor / Media Manager</strong><p>Content-focused roles for website text, news, SEO and approved media.</p></article><article><strong>Auditor</strong><p>Oversight-focused access to reports, finance and audit records, without editing authority.</p></article></div></section></main>
}