import Link from "next/link";
import {constitution} from "../data/constitution";
import {registerMemberAction} from "./actions";

export const metadata={title:"Join MWONET",description:"Create a secure MWONET member account and submit your membership profile for review."};

export default async function Register({searchParams}:{searchParams:Promise<{error?:string}>}){
 const {error}=await searchParams;const m=constitution.membership;
 return <section className="auth-page member-auth-page"><div className="auth-visual register-bg"><div><p className="eyebrow light">JOIN MWONET</p><h1>Build your membership record securely.</h1><p>Membership is constitutionally designed for young people aged {m.age} who live or operate within Bungoma County/Region and agree to abide by the organization’s constitution.</p><div className="auth-facts"><span><b>Registration</b>{m.registrationFee}</span><span><b>Monthly</b>{m.monthlySubscription}</span><span><b>Approval</b>Applications are reviewed by MWONET administration.</span></div></div></div><div className="auth-panel"><div className="auth-box auth-box-wide"><p className="eyebrow">SECURE MEMBER REGISTRATION</p><h2>Create your account</h2><p className="auth-note">Your account is created immediately for secure portal access, while your constitutional membership status remains <strong>Pending</strong> until reviewed by MWONET. No online payment is collected on this form.</p>{error&&<div className="auth-error">{error}</div>}<form action={registerMemberAction} className="member-form"><div className="member-form-grid"><label>Full name<input name="name" autoComplete="name" required placeholder="Your full legal name"/></label><label>Email address<input name="email" type="email" autoComplete="email" required placeholder="name@example.com"/></label><label>Phone number<input name="phone" type="tel" autoComplete="tel" required placeholder="+254 7XX XXX XXX"/></label><label>Date of birth<input name="dateOfBirth" type="date" required/></label><label>Membership area<select name="county" defaultValue="Bungoma County" required><option>Bungoma County</option></select></label><label>Password<input name="password" type="password" autoComplete="new-password" minLength={10} required placeholder="10+ characters"/></label><label>Confirm password<input name="confirmPassword" type="password" autoComplete="new-password" minLength={10} required/></label></div><label className="check-row"><input name="areaConfirmed" type="checkbox" required/><span>I confirm that I live or operate within Bungoma County/Region.</span></label><label className="check-row"><input name="constitutionAccepted" type="checkbox" required/><span>I have read the <Link href="/constitution" target="_blank">MWONET Constitution</Link> and agree to abide by it.</span></label><button className="button primary full" type="submit">Create secure member account</button></form><div className="auth-help"><p>Already registered? <Link href="/sign-in">Sign in to your portal</Link></p><p><Link href="/membership">Review membership requirements →</Link></p></div></div></div></section>
}
