import Link from "next/link";import PageHero from "../components/PageHero";import {images} from "../data/site";import {constitution} from "../data/constitution";
const articles=[
 ["Article 1","Name & Office","MWONET is Maanisha Western Organization Network, headquartered in Kapkatenyi, Kopsiro Sub-County, Bungoma County, Kenya."],
 ["Article 2","Vision, Mission & Objectives","Environmental conservation, agribusiness and livestock, coffee cash-crop development, and financial pooling/micro-credit."],
 ["Article 3","Core Values","Unity, integrity and accountability, environmental responsibility, innovation and self-reliance."],
 ["Article 4","Membership","Eligibility, registration, subscriptions, member rights and termination rules."],
 ["Article 5","Management & Governance","An elected six-office Executive Committee with defined duties."],
 ["Article 6","Meetings","Regular meetings, an annual AGM and a quorum threshold that still requires final confirmation."],
 ["Article 7","Finance & Loaning","Bank controls, fund sources and internal revolving-fund principles."],
 ["Article 8","Amendment","Constitutional changes require a two-thirds majority at a properly convened AGM or Special General Meeting."],
 ["Article 9","Dissolution","Dissolution requires a three-quarters vote of all registered members and settlement of local debts."],
];
export default function Constitution(){return <><PageHero eyebrow="Constitution" title="The framework behind MWONET’s purpose, membership and accountability." text="This digital summary is based on the organization’s current constitution and is presented to make its structure easier for members, partners and the public to understand." image={images.mountain}/><section className="section"><div className="container intro-grid"><div><p className="eyebrow">VISION</p><h2>{constitution.vision}</h2></div><div><p className="eyebrow">MISSION</p><p className="big-copy">{constitution.mission}</p><p className="notice">Where the source constitution contains placeholders or unresolved wording, the website marks those items for formal confirmation instead of guessing.</p></div></div></section><section className="section tint"><div className="container article-grid">{articles.map(([number,title,text])=><article className="article-card" key={number}><small>{number}</small><h3>{title}</h3><p>{text}</p></article>)}</div></section><section className="section"><div className="container cta-box"><div><p className="eyebrow">EXPLORE THE STRUCTURE</p><h2>Turn constitutional principles into working systems.</h2></div><div className="cta-actions"><Link className="button primary" href="/membership">Membership</Link><Link className="button primary" href="/governance">Governance</Link><Link className="button primary" href="/financial-model">Finance</Link></div></div></section></>}
