import {getAdminSession} from "../../_lib/auth";
import {getUserAccess,requirePermission} from "../../_lib/access";
import {db} from "../../_lib/db";
import {ensureSystemCatalog} from "../../_lib/cms";
import {assignRoleAction,promoteLeadershipAction,removeRoleAction,resetUserPasswordAction,updateUserStatusAction} from "./actions";

export const dynamic="force-dynamic";

export default async function UsersPage(){
 const session=await getAdminSession();if(!session)throw new Error("Not signed in");
 await requirePermission(session.email,"manage_users");const access=await getUserAccess(session.email);const isSuper=access.isSuperAdmin;
 await ensureSystemCatalog();
 const [users,roles]=await Promise.all([
  db.user.findMany({orderBy:{createdAt:"desc"},include:{roles:{include:{role:true}},member:true}}),
  db.role.findMany({where:{name:{not:"Super Admin"}},orderBy:{name:"asc"}})
 ]);
 const manageable=users.filter(u=>!u.roles.some(r=>r.role.name==="Super Admin"));
 const active=users.filter(u=>u.status==="ACTIVE").length,members=users.filter(u=>u.member).length,staff=users.filter(u=>u.roles.some(r=>r.role.name!=="Super Admin")).length;
 return <main className="admin-content">
  <div className="admin-page-head"><div><span className="admin-breadcrumb">MWONET Admin / People</span><h1>Users & Access</h1><p>Manage registered accounts, account status and operational access. Super Admin alone assigns roles, promotes leaders and resets another person’s password.</p></div><span className="admin-badge">{users.length} accounts</span></div>
  <section className="admin-stat-grid"><article className="admin-stat"><small>TOTAL</small><strong>{users.length}</strong><span>Registered accounts</span></article><article className="admin-stat"><small>ACTIVE</small><strong>{active}</strong><span>Enabled sign-ins</span></article><article className="admin-stat"><small>MEMBERS</small><strong>{members}</strong><span>Membership profiles</span></article><article className="admin-stat"><small>STAFF / LEADERS</small><strong>{staff}</strong><span>Role-assigned users</span></article></section>
  <section className="admin-panel"><div className="admin-panel-head"><h2>User directory</h2><span className="admin-badge">Super Admin protected</span></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Person</th><th>Membership</th><th>Roles</th><th>Account status</th><th>{isSuper?"Grant role":"Access"}</th></tr></thead><tbody>{users.map(u=>{const superUser=u.roles.some(x=>x.role.name==="Super Admin");return <tr key={u.id}><td><strong>{u.name||"Unnamed user"}</strong><small>{u.email}<br/>{u.lastLoginAt?"Last sign-in "+u.lastLoginAt.toLocaleString("en-KE"):"Never signed in"}</small></td><td>{u.member?<><span className="admin-badge">{u.member.status}</span><small>{u.member.memberNumber||"Number pending"}</small></>:"—"}</td><td><div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{u.roles.length?u.roles.map(r=>isSuper?<form key={r.roleId} action={removeRoleAction}><input type="hidden" name="userId" value={u.id}/><input type="hidden" name="roleId" value={r.roleId}/><button className="admin-badge" disabled={r.role.name==="Super Admin"} title={r.role.name==="Super Admin"?"Owner role cannot be removed here":"Remove role"}>{r.role.name}{r.role.name==="Super Admin"?" 🔒":" ×"}</button></form>:<span className="admin-badge" key={r.roleId}>{r.role.name}</span>):<span>Member / public user</span>}</div></td><td>{superUser?<span className="admin-badge">ACTIVE · protected</span>:<form action={updateUserStatusAction} className="admin-inline-form"><input type="hidden" name="userId" value={u.id}/><select name="status" defaultValue={u.status}><option>ACTIVE</option><option>INVITED</option><option>SUSPENDED</option><option>DISABLED</option></select><button className="admin-secondary">Save</button></form>}</td><td>{superUser?"Owner account":!isSuper?"Super Admin assigns roles":<form action={assignRoleAction} className="admin-inline-form"><input type="hidden" name="userId" value={u.id}/><select name="roleName" defaultValue=""><option value="" disabled>Select role</option>{roles.map(r=><option key={r.id}>{r.name}</option>)}</select><button className="admin-secondary">Assign</button></form>}</td></tr>})}</tbody></table></div></section>
  {isSuper&&<><section className="admin-panel"><div className="admin-panel-head"><h2>Promote a registered person into leadership</h2><span className="admin-badge">Same account</span></div><p className="admin-section-note">Use this when a member or user becomes Chairperson, Secretary, Treasurer, Project Manager or another official. Their existing account is upgraded; do not create duplicate accounts.</p><form action={promoteLeadershipAction} className="admin-form admin-form-grid"><label>User<select name="userId" required><option value="">Select registered user</option>{manageable.map(u=><option key={u.id} value={u.id}>{u.name||u.email} - {u.email}</option>)}</select></label><label>Admin access role<select name="roleName"><option value="">Leadership profile only</option>{roles.map(r=><option key={r.id}>{r.name}</option>)}</select></label><label>Official leadership title<input name="title" placeholder="e.g. Chairperson, Secretary, Treasurer" required/></label><label className="admin-span-2">Short biography / responsibility<textarea name="bio" rows={4} placeholder="Describe the official's responsibility, experience or portfolio."/></label><button className="admin-primary">Promote / update leadership</button></form></section>
  <section className="admin-panel"><div className="admin-panel-head"><h2>Administrator-assisted password reset</h2><span className="admin-badge">Super Admin only</span></div><p className="admin-section-note">Use this when a member or staff user cannot access their account and outbound reset email is unavailable. Set a temporary password, communicate it privately, then ask the user to sign in and change it immediately from the member portal.</p><form action={resetUserPasswordAction} className="admin-form admin-form-grid"><label>User<select name="userId" required><option value="">Select user</option>{manageable.map(u=><option key={u.id} value={u.id}>{u.name||u.email} - {u.email}</option>)}</select></label><label>Temporary password<input name="temporaryPassword" type="password" minLength={10} required placeholder="10+ chars, upper/lowercase and number"/></label><button className="admin-primary">Set temporary password</button></form><p className="admin-section-note">The old password is never displayed. The temporary password itself is not written to the audit log.</p></section></>}
  <section className="admin-panel"><div className="admin-panel-head"><h2>Access model</h2></div><div className="admin-info-grid"><article><strong>Super Admin</strong><p>Owner-level access only. Protected from ordinary role changes and permanent deletion controls.</p></article><article><strong>Administrator</strong><p>Normal day-to-day editing and administration without owner-only themes, plugins, roles or destructive system control.</p></article><article><strong>Leadership roles</strong><p>Chairperson, Secretary and Treasurer receive only the areas required for their responsibilities.</p></article><article><strong>Members</strong><p>A normal member uses the member portal and receives no admin access until Super Admin deliberately assigns an operational role.</p></article></div></section>
 </main>
}
