import Link from "next/link";
import {notFound} from "next/navigation";
import {db} from "../../../_lib/db";
import {getCmsPage,slugToPublicPath} from "../../../_lib/cms";
import {restoreRevisionAction,savePageAction} from "./actions";

export const dynamic="force-dynamic";

export default async function AdminPageEditor({params,searchParams}:{params:Promise<{slug:string}>,searchParams:Promise<{saved?:string;created?:string;restored?:string}>}){
 const {slug}=await params;const sp=await searchParams;const page=await getCmsPage(slug);if(!page)return notFound();const path=slugToPublicPath(slug);
 const block=(position:number)=>page.blocks.find(b=>b.position===position)?.data as Record<string,unknown>|undefined;
 const hero=block(0)||{},rich=block(1)||{},image=block(2)||{},cta=block(3)||{},gallery=block(4)||{},stats=block(5)||{},video=block(6)||{},downloads=block(7)||{},formBlock=block(8)||{},settings=block(9)||{};
 const forms=await db.form.findMany({orderBy:{name:"asc"}});
 const str=(v:unknown)=>typeof v==="string"?v:"";const lines=(v:unknown)=>Array.isArray(v)?v.join("\n"):"";
 return <main className="admin-content">
  <div className="admin-page-head"><div><span className="admin-breadcrumb">MWONET Admin / Pages / {page.title}</span><h1>Edit {page.title}</h1><p>One complete workspace for layout, content, media, calls-to-action, forms, SEO, publishing and revision recovery.</p></div><div className="admin-inline-actions"><Link className="admin-secondary" href="/admin/pages">← All pages</Link><Link className="admin-secondary" href={path} target="_blank">Public view ↗</Link></div></div>
  {(sp.saved||sp.created)&&<div className="admin-success">✓ Page saved successfully. Revision history and audit tracking are active.</div>}{sp.restored&&<div className="admin-success">✓ Revision restored successfully. A backup of the replaced version was created automatically.</div>}
  <form action={savePageAction} className="admin-page-editor"><input type="hidden" name="slug" value={slug}/><div>
   <section className="admin-editor-section"><h3>Page identity</h3><div className="admin-form admin-form-grid"><label>Page title<input name="title" defaultValue={page.title} required/></label><label>Public URL<input value={path} readOnly/></label><label>Template<select name="template" defaultValue={str(settings.template)||"standard"}><option value="standard">Standard content</option><option value="landing">Landing page</option><option value="story">Story / campaign</option><option value="directory">Directory / listing</option><option value="minimal">Minimal</option></select></label><label>Visibility<select name="visibility" defaultValue={str(settings.visibility)||"public"}><option value="public">Public</option><option value="members">Members only</option><option value="private">Private/admin only</option></select></label></div></section>
   <section className="admin-editor-section"><h3>Hero section</h3><div className="admin-form"><label>Eyebrow / section label<input name="heroEyebrow" defaultValue={str(hero.eyebrow)} placeholder="ABOUT MWONET"/></label><label>Hero heading<textarea name="heroHeading" rows={3} defaultValue={str(hero.heading)} placeholder="Main page headline"/></label><label>Introductory text<textarea name="heroText" rows={4} defaultValue={str(hero.text)} placeholder="Short page introduction"/></label><label>Hero image URL<input name="heroImage" defaultValue={str(hero.image)} placeholder="https://..."/></label><div className="admin-form-grid"><label>Hero button label<input name="heroButtonLabel" defaultValue={str(hero.buttonLabel)} placeholder="Explore our work"/></label><label>Hero button link<input name="heroButtonHref" defaultValue={str(hero.buttonHref)} placeholder="/focus-areas"/></label></div></div></section>
   <section className="admin-editor-section"><h3>Main content</h3><div className="admin-form"><label>Section heading<input name="richHeading" defaultValue={str(rich.heading)}/></label><label>Body content<textarea name="richBody" rows={12} defaultValue={str(rich.body)} placeholder="Write the main page content here. Use clear paragraphs and factual MWONET information."/></label></div></section>
   <section className="admin-editor-section"><h3>Feature image</h3><div className="admin-form admin-form-grid"><label className="admin-span-2">Image URL<input name="featureImage" defaultValue={str(image.url)} placeholder="https://..."/></label><label>Alternative text<input name="featureAlt" defaultValue={str(image.alt)} placeholder="Describe the image for accessibility"/></label><label>Caption<input name="featureCaption" defaultValue={str(image.caption)}/></label></div></section>
   <section className="admin-editor-section"><h3>Gallery</h3><div className="admin-form"><label>Gallery heading<input name="galleryHeading" defaultValue={str(gallery.heading)} placeholder="From the field"/></label><label>Image URLs — one per line<textarea name="galleryImages" rows={7} defaultValue={lines(gallery.images)} placeholder={"https://...\nhttps://...\nhttps://..."}/></label><p className="admin-section-note">Use high-quality Kenyan/African community, Mount Elgon, nursery, agriculture and project imagery. Avoid duplicates and unclear stock photos.</p></div></section>
   <section className="admin-editor-section"><h3>Impact statistics</h3><div className="admin-form"><label>Section heading<input name="statsHeading" defaultValue={str(stats.heading)} placeholder="Our impact"/></label><label>Statistics — one per line<textarea name="statsItems" rows={6} defaultValue={lines(stats.items)} placeholder={"10,000+ | Seedlings raised\n250+ | Young people reached\n12 | Community activities"}/></label><p className="admin-section-note">Use the format “number | label”. Only publish figures MWONET can support with records.</p></div></section>
   <section className="admin-editor-section"><h3>Video</h3><div className="admin-form"><label>Video heading<input name="videoHeading" defaultValue={str(video.heading)}/></label><label>YouTube / video URL<input name="videoUrl" defaultValue={str(video.url)} placeholder="https://youtube.com/..."/></label><label>Caption<textarea name="videoCaption" rows={3} defaultValue={str(video.caption)}/></label></div></section>
   <section className="admin-editor-section"><h3>Downloads & documents</h3><div className="admin-form"><label>Section heading<input name="downloadsHeading" defaultValue={str(downloads.heading)} placeholder="Downloads"/></label><label>Items — one per line<textarea name="downloadsItems" rows={6} defaultValue={lines(downloads.items)} placeholder={"MWONET Constitution | /documents/constitution.pdf\nAnnual Report | https://..."}/></label><p className="admin-section-note">Use “label | URL” for each document.</p></div></section>
   <section className="admin-editor-section"><h3>Embedded form</h3><div className="admin-form"><label>Section heading<input name="formHeading" defaultValue={str(formBlock.heading)} placeholder="Send your details"/></label><label>Supporting text<textarea name="formText" rows={3} defaultValue={str(formBlock.text)}/></label><label>Form<select name="formKey" defaultValue={str(formBlock.formKey)}><option value="">No form</option>{forms.map(f=><option key={f.id} value={f.key}>{f.name}</option>)}</select></label></div></section>
   <section className="admin-editor-section"><h3>Call to action</h3><div className="admin-form admin-form-grid"><label>Heading<input name="ctaHeading" defaultValue={str(cta.heading)}/></label><label>Button label<input name="ctaLabel" defaultValue={str(cta.label)} placeholder="Get involved"/></label><label className="admin-span-2">Supporting text<textarea name="ctaText" rows={3} defaultValue={str(cta.text)}/></label><label className="admin-span-2">Button link<input name="ctaHref" defaultValue={str(cta.href)} placeholder="/get-involved"/></label></div></section>
  </div><aside className="admin-side-stack">
   <section className="admin-editor-section admin-sticky-card"><h3>Publish</h3><div className="admin-form"><label>Status<select name="status" defaultValue={page.status.toLowerCase()}><option value="draft">Draft</option><option value="review">In review</option><option value="published">Published</option><option value="scheduled">Scheduled</option><option value="archived">Archived</option></select></label><label>Schedule date/time<input type="datetime-local" name="scheduledAt" defaultValue={page.scheduledAt?new Date(page.scheduledAt.getTime()-page.scheduledAt.getTimezoneOffset()*60000).toISOString().slice(0,16):""}/></label><button className="admin-primary" type="submit">Save page</button></div><div className="admin-publish-meta"><small>Published: {page.publishedAt?page.publishedAt.toLocaleString("en-KE"):"Not yet"}</small><small>Updated: {page.updatedAt.toLocaleString("en-KE")}</small></div></section>
   <section className="admin-editor-section"><h3>SEO & discovery</h3><div className="admin-form"><label>SEO title<input name="seoTitle" defaultValue={page.seoTitle||`${page.title} | MWONET`}/></label><label>Meta description<textarea name="description" rows={5} defaultValue={page.description||""}/></label><label>Social share image<input name="socialImage" defaultValue={page.socialImage||""} placeholder="Image URL"/></label><label>Canonical URL<input name="canonical" defaultValue={str(settings.canonical)} placeholder={`https://mwonet.org${path}`}/></label><label className="admin-check"><input type="checkbox" name="noIndex" defaultChecked={settings.noIndex===true}/> Hide this page from search engines</label></div></section>
   <section className="admin-editor-section"><h3>Publishing checklist</h3><div className="admin-config-list"><span className="admin-section-note">✓ Official facts and constitution wording checked</span><span className="admin-section-note">✓ Images have useful alt text</span><span className="admin-section-note">✓ Mobile layout and links checked</span><span className="admin-section-note">✓ SEO title and description completed</span><span className="admin-section-note">✓ Statistics supported by records</span></div></section>
   <section className="admin-editor-section"><h3>Revision history</h3>{page.revisions.length===0?<p className="admin-section-note">No revisions yet.</p>:<div className="admin-revision-list">{page.revisions.map(r=><div key={r.id}><strong>{r.createdAt.toLocaleString("en-KE")}</strong><small>{r.author?.email||"System"}</small><span>{r.note||"Page revision"}</span><form action={restoreRevisionAction}><input type="hidden" name="slug" value={slug}/><input type="hidden" name="revisionId" value={r.id}/><button className="admin-link-button" type="submit">Restore this version</button></form></div>)}</div>}</section>
  </aside></form>
 </main>
}
