import Link from "next/link";
import {notFound} from "next/navigation";
import {getCmsPage,slugToPublicPath} from "../../../_lib/cms";
import {savePageAction} from "./actions";

export const dynamic="force-dynamic";

export default async function AdminPageEditor({params,searchParams}:{params:Promise<{slug:string}>,searchParams:Promise<{saved?:string}>}){
 const {slug}=await params;const {saved}=await searchParams;const page=await getCmsPage(slug);if(!page)return notFound();
 const path=slugToPublicPath(slug);
 const block=(position:number)=>page.blocks.find(b=>b.position===position)?.data as Record<string,string>|undefined;
 const hero=block(0)||{},rich=block(1)||{},image=block(2)||{},cta=block(3)||{};
 return <main className="admin-content">
  <div className="admin-page-head"><div><span className="admin-breadcrumb">MWONET Admin / Pages / {page.title}</span><h1>Edit {page.title}</h1><p>Manage hero content, body copy, feature media, call-to-action, SEO and publishing from one workspace. Every save creates a database revision and audit record.</p></div><div style={{display:"flex",gap:8}}><Link className="admin-secondary" href={path} target="_blank">Preview ↗</Link></div></div>
  {saved&&<div className="admin-success">✓ Changes saved successfully. A revision and audit record were created.</div>}
  <form action={savePageAction} className="admin-page-editor"><input type="hidden" name="slug" value={slug}/><div>
   <section className="admin-editor-section"><h3>Page identity</h3><div className="admin-form admin-form-grid"><label>Page title<input name="title" defaultValue={page.title} required/></label><label>Public URL<input value={path} readOnly/></label></div></section>
   <section className="admin-editor-section"><h3>Hero section</h3><div className="admin-form"><label>Eyebrow / section label<input name="heroEyebrow" defaultValue={hero.eyebrow||""} placeholder="ABOUT MWONET"/></label><label>Hero heading<textarea name="heroHeading" rows={3} defaultValue={hero.heading||""} placeholder="Main page headline"/></label><label>Introductory text<textarea name="heroText" rows={4} defaultValue={hero.text||""} placeholder="Short page introduction"/></label><label>Hero image URL<input name="heroImage" defaultValue={hero.image||""} placeholder="https://..."/></label></div></section>
   <section className="admin-editor-section"><h3>Rich text section</h3><div className="admin-form"><label>Section heading<input name="richHeading" defaultValue={rich.heading||""}/></label><label>Body content<textarea name="richBody" rows={9} defaultValue={rich.body||""} placeholder="Write the main page content here..."/></label></div></section>
   <section className="admin-editor-section"><h3>Feature image</h3><div className="admin-form admin-form-grid"><label className="admin-span-2">Image URL<input name="featureImage" defaultValue={image.url||""} placeholder="https://..."/></label><label>Alternative text<input name="featureAlt" defaultValue={image.alt||""} placeholder="Describe the image for accessibility"/></label><label>Caption<input name="featureCaption" defaultValue={image.caption||""}/></label></div></section>
   <section className="admin-editor-section"><h3>Call to action</h3><div className="admin-form admin-form-grid"><label>Heading<input name="ctaHeading" defaultValue={cta.heading||""}/></label><label>Button label<input name="ctaLabel" defaultValue={cta.label||""} placeholder="Get involved"/></label><label className="admin-span-2">Supporting text<textarea name="ctaText" rows={3} defaultValue={cta.text||""}/></label><label className="admin-span-2">Button link<input name="ctaHref" defaultValue={cta.href||""} placeholder="/get-involved"/></label></div></section>
   <section className="admin-editor-section"><h3>Block roadmap</h3><div className="admin-quick-grid"><span className="admin-section-note">Hero ✓</span><span className="admin-section-note">Rich text ✓</span><span className="admin-section-note">Feature image ✓</span><span className="admin-section-note">CTA ✓</span><span className="admin-section-note">Gallery next</span><span className="admin-section-note">Stats next</span><span className="admin-section-note">Video next</span><span className="admin-section-note">Forms next</span></div></section>
  </div><aside className="admin-side-stack">
   <section className="admin-editor-section"><h3>Publish</h3><div className="admin-form"><label>Status<select name="status" defaultValue={page.status.toLowerCase()}><option value="draft">Draft</option><option value="review">In review</option><option value="published">Published</option><option value="scheduled">Scheduled</option><option value="archived">Archived</option></select></label><button className="admin-primary" type="submit">Save changes</button></div></section>
   <section className="admin-editor-section"><h3>SEO</h3><div className="admin-form"><label>SEO title<input name="seoTitle" defaultValue={page.seoTitle||`${page.title} | MWONET`}/></label><label>Meta description<textarea name="description" rows={4} defaultValue={page.description||""}/></label><label>Social image<input name="socialImage" defaultValue={page.socialImage||""} placeholder="Image URL"/></label></div></section>
   <section className="admin-editor-section"><h3>Publishing checklist</h3><div className="admin-config-list"><span className="admin-section-note">Use approved MWONET facts and constitution wording.</span><span className="admin-section-note">Use clear Kenyan/African imagery with meaningful alt text.</span><span className="admin-section-note">Check mobile layout and links before publishing.</span><span className="admin-section-note">Keep SEO title and description specific to the page.</span></div></section>
   <section className="admin-editor-section"><h3>Revision history</h3>{page.revisions.length===0?<p className="admin-section-note">No revisions yet.</p>:<div className="admin-revision-list">{page.revisions.map(r=><div key={r.id}><strong>{r.createdAt.toLocaleString("en-KE")}</strong><small>{r.author?.email||"System"}</small><span>{r.note||"Page revision"}</span></div>)}</div>}</section>
  </aside></form>
 </main>
}
