import Link from "next/link";
import {getAdminSession} from "../../_lib/auth";
import {requirePermission} from "../../_lib/access";
import {db} from "../../_lib/db";
import {createEventAdmin} from "./actions";

export const dynamic="force-dynamic";
export default async function EventsAdmin(){
 const session=await getAdminSession();if(!session)throw new Error("Not signed in");await requirePermission(session.email,"manage_events");
 const rows=await db.event.findMany({orderBy:{startsAt:"desc"},include:{_count:{select:{registrations:true}}}});
 const upcoming=rows.filter(e=>e.startsAt>=new Date()).length,published=rows.filter(e=>e.status==="PUBLISHED").length,registrations=rows.reduce((s,e)=>s+e._count.registrations,0);
 return <main className="admin-content"><div className="admin-page-head"><div><span className="admin-breadcrumb">MWONET Admin / Content</span><h1>Events</h1><p>Create public events, manage dates and venues, receive registrations and record attendance from one place.</p></div><span className="admin-badge">{rows.length} events</span></div>
 <section className="admin-stat-grid"><article className="admin-stat"><small>UPCOMING</small><strong>{upcoming}</strong><span>Current or future events</span></article><article className="admin-stat"><small>PUBLISHED</small><strong>{published}</strong><span>Visible on website</span></article><article className="admin-stat"><small>REGISTRATIONS</small><strong>{registrations}</strong><span>Total event registrations</span></article><article className="admin-stat"><small>WORKFLOW</small><strong>Draft → Publish</strong><span>Controlled public visibility</span></article></section>
 <div className="admin-grid"><section className="admin-panel"><div className="admin-panel-head"><h2>Event register</h2></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Event</th><th>Status</th><th>Venue</th><th>Starts</th><th>Registrations</th><th>Actions</th></tr></thead><tbody>{rows.length?rows.map(e=><tr key={e.id}><td><strong>{e.title}</strong><small>{e.slug}</small></td><td><span className="admin-badge">{e.status}</span></td><td>{e.venue||"—"}</td><td>{e.startsAt.toLocaleString("en-KE")}</td><td>{e._count.registrations}</td><td><Link className="admin-action-link" href={`/admin/edit/event/${e.id}`}>Edit →</Link> · <Link className="admin-action-link" href={`/admin/events/${e.id}/registrations`}>Attendance →</Link>{e.status==="PUBLISHED"&&<> · <Link className="admin-action-link" href={`/events/${e.slug}`} target="_blank">View ↗</Link></>}</td></tr>):<tr><td colSpan={6}>No events yet.</td></tr>}</tbody></table></div></section>
 <aside className="admin-side-stack"><section className="admin-editor-section"><h3>Create event</h3><form action={createEventAdmin} className="admin-form"><label>Event title<input name="title" required/></label><label>Slug (optional)<input name="slug"/></label><label>Venue<input name="venue"/></label><label>Starts<input name="startsAt" type="datetime-local" required/></label><label>Ends<input name="endsAt" type="datetime-local"/></label><label>Status<select name="status"><option>DRAFT</option><option>REVIEW</option><option>PUBLISHED</option></select></label><label>Description<textarea name="description" rows={5}/></label><button className="admin-primary">Create event</button></form></section><section className="admin-editor-section"><h3>How attendance works</h3><p className="admin-section-note">A published event receives its own public page. Visitors can register with name, email and phone. Staff then open Attendance to mark each record Registered, Attended or Cancelled.</p></section></aside></div></main>
}
