import {getAdminSession} from "../../_lib/auth";
import {requirePermission} from "../../_lib/access";
import {db} from "../../_lib/db";
import {ensureSystemCatalog} from "../../_lib/cms";
import {activateThemeAction,createThemePresetAction} from "./actions";

export const dynamic="force-dynamic";

export default async function AdminThemes(){
 const session=await getAdminSession();if(!session)throw new Error("Not signed in");await requirePermission(session.email,"manage_themes");
 await ensureSystemCatalog();const themes=await db.theme.findMany({orderBy:[{active:"desc"},{name:"asc"}]});
 return <main className="admin-content"><div className="admin-page-head"><div><span className="admin-breadcrumb">MWONET Admin / Website</span><h1>Themes</h1><p>Change the public website’s visual identity using safe design presets. Activating a theme changes the site colours without changing content, accounts or database records.</p></div><span className="admin-badge">{themes.length} installed</span></div>
 <div className="admin-theme-grid">{themes.map(t=>{const manifest=t.manifest as {description?:string};const settings=(t.settings||{}) as Record<string,string>;return <article className="admin-theme-card" key={t.id}><div className="admin-theme-preview" style={{background:`linear-gradient(145deg,${settings.dark||"#17382f"} 0 34%,${settings.primary||"#0a7748"} 34% 66%,${settings.pale||"#f2f7f4"} 66%)`}}/><div><span className={`admin-badge ${t.active?"":"gray"}`}>{t.active?"Active":"Available"}</span><h3>{t.name}</h3><p>{manifest.description||"MWONET compatible theme."}</p><small>Version {t.version}</small><div style={{display:"flex",gap:8,marginTop:14}}><form action={activateThemeAction}><input type="hidden" name="key" value={t.key}/><button className="admin-primary" type="submit" disabled={t.active}>{t.active?"Active":"Activate"}</button></form></div></div></article>})}</div>
 <section className="admin-panel" style={{marginTop:18}}><div className="admin-panel-head"><h2>Create or update a safe custom theme</h2><span className="admin-badge">Super Admin only</span></div><p className="admin-section-note">Instead of uploading unsafe WordPress/PHP code, MWONET lets the owner create reusable design presets using controlled colours. This gives WordPress-like theme switching while protecting member data and credentials.</p><form action={createThemePresetAction} className="admin-form admin-form-grid"><label>Theme name<input name="name" required placeholder="e.g. MWONET Earth & Gold"/></label><label>Theme key<input name="key" placeholder="earth-gold"/></label><label>Primary colour<input name="primary" type="color" defaultValue="#0a7748"/></label><label>Dark colour<input name="dark" type="color" defaultValue="#0d3428"/></label><label>Accent colour<input name="accent" type="color" defaultValue="#9de2b8"/></label><label>Pale background<input name="pale" type="color" defaultValue="#f2f7f4"/></label><label>Text colour<input name="text" type="color" defaultValue="#16372c"/></label><label className="admin-span-2">Description<textarea name="description" rows={3} placeholder="When and why this visual style should be used."/></label><button className="admin-primary">Save theme preset</button></form></section>
 <section className="admin-panel"><div className="admin-panel-head"><h2>Theme safety rules</h2></div><div className="admin-config-list"><span className="admin-section-note">Theme changes affect colours and approved visual tokens, not database content or user permissions.</span><span className="admin-section-note">Arbitrary WordPress/PHP themes are not executed because this platform is Next.js, not WordPress.</span><span className="admin-section-note">The active theme can be changed at any time by Super Admin without redeploying the website.</span></div></section></main>
}
