import {db} from "../../_lib/db";
import {ensureSystemCatalog} from "../../_lib/cms";
import {activateThemeAction} from "./actions";

export const dynamic="force-dynamic";

export default async function AdminThemes(){
 await ensureSystemCatalog();
 const themes=await db.theme.findMany({orderBy:[{active:"desc"},{name:"asc"}]});
 return <main className="admin-content"><div className="admin-page-head"><div><span className="admin-breadcrumb">MWONET Admin / Website</span><h1>Themes</h1><p>WordPress-inspired visual theme management using safe MWONET-compatible theme packages. Theme selection is now stored in the database and audited.</p></div><span className="admin-badge">{themes.length} installed</span></div><div className="admin-theme-grid">{themes.map((t,i)=>{const manifest=t.manifest as {description?:string};return <article className="admin-theme-card" key={t.id}><div className="admin-theme-preview" style={i===1?{background:"linear-gradient(145deg,#263d31 0 30%,#9db39c 30% 60%,#e6ddc5 60%)"}:i===2?{background:"linear-gradient(145deg,#0c6b44 0 35%,#dcefe3 35% 68%,#f4d9aa 68%)"}:i===3?{background:"linear-gradient(145deg,#1e3341 0 30%,#f3f5f6 30% 70%,#d8e2e7 70%)"}:i===4?{background:"linear-gradient(145deg,#126c50 0 30%,#f2bf63 30% 55%,#eef5f1 55%)"}:undefined}/><div><span className={`admin-badge ${t.active?"":"gray"}`}>{t.active?"Active":"Available"}</span><h3>{t.name}</h3><p>{manifest.description||"MWONET compatible theme."}</p><small>Version {t.version}</small><div style={{display:"flex",gap:8,marginTop:14}}><button className="admin-secondary" type="button">Preview</button><form action={activateThemeAction}><input type="hidden" name="key" value={t.key}/><button className="admin-primary" type="submit" disabled={t.active}>{t.active?"Active":"Activate"}</button></form></div></div></article>})}</div><section className="admin-panel" style={{marginTop:18}}><div className="admin-panel-head"><h2>Theme package rules</h2></div><p className="admin-section-note">For security, MWONET themes use controlled design tokens, layout presets and approved React components. Arbitrary WordPress/PHP theme code is never executed. This prevents a theme upload from compromising administrator credentials or member data.</p></section></main>}
